language: go
jobs:
  include:
    - os: linux
      dist: trusty
      go: 1.13.x
    - os: osx
      osx_image: xcode11.2
      go: 1.13.x
# TODO(prasadgopal): running of master is broken as of 12/17/2019.
# Re evaluate if we should even test of golang master.
#    - os: linux
#      dist: trusty
#      go: master
#    - os: osx
#      osx_image: xcode11.2
#      go: master
install: true
script:
  - env GO111MODULE=on go test -v -tags unit ./...
