// Code generated by "stringer -type=FlowState"; DO NOT EDIT

package reflow

import "fmt"

const _FlowState_name = "FlowInitFlowNeedLookupFlowLookupFlowTODOFlowNeedTransferFlowTransferFlowReadyFlowRunningFlowDoneFlowMax"

var _FlowState_index = [...]uint8{0, 8, 22, 32, 40, 56, 68, 77, 88, 96, 103}

func (i FlowState) String() string {
	if i < 0 || i >= FlowState(len(_FlowState_index)-1) {
		return fmt.Sprintf("FlowState(%d)", i)
	}
	return _FlowState_name[_FlowState_index[i]:_FlowState_index[i+1]]
}
