// Copyright 2017 GRAIL, Inc. All rights reserved.
// Use of this source code is governed by the Apache 2.0
// license that can be found in the LICENSE file.

// Code generated by "stringer -type=FlowState"; DO NOT EDIT

package reflow

import "fmt"

const _FlowState_name = "FlowInitFlowNeedLookupFlowLookupFlowNeedTransferFlowTransferFlowTODOFlowReadyFlowRunningFlowDoneFlowMax"

var _FlowState_index = [...]uint8{0, 8, 22, 32, 48, 60, 68, 77, 88, 96, 103}

func (i FlowState) String() string {
	if i < 0 || i >= FlowState(len(_FlowState_index)-1) {
		return fmt.Sprintf("FlowState(%d)", i)
	}
	return _FlowState_name[_FlowState_index[i]:_FlowState_index[i+1]]
}
