// Copyright 2017 GRAIL, Inc. All rights reserved.
// Use of this source code is governed by the Apache 2.0
// license that can be found in the LICENSE file.

// Code generated by "stringer -type=State"; DO NOT EDIT

package batch

import "fmt"

const _State_name = "StateInitStateRunningStateDoneStateErrorstateMax"

var _State_index = [...]uint8{0, 9, 21, 30, 40, 48}

func (i State) String() string {
	if i < 0 || i >= State(len(_State_index)-1) {
		return fmt.Sprintf("State(%d)", i)
	}
	return _State_name[_State_index[i]:_State_index[i+1]]
}
