// Code generated by "stringer -type=Mutation"; DO NOT EDIT.

package flow

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Invalid-0]
	_ = x[Cached-1]
	_ = x[Refresh-2]
	_ = x[MustIntern-3]
	_ = x[NoStatus-4]
	_ = x[Propagate-5]
}

const _Mutation_name = "InvalidCachedRefreshMustInternNoStatusPropagate"

var _Mutation_index = [...]uint8{0, 7, 13, 20, 30, 38, 47}

func (i Mutation) String() string {
	if i < 0 || i >= Mutation(len(_Mutation_index)-1) {
		return "Mutation(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Mutation_name[_Mutation_index[i]:_Mutation_index[i+1]]
}
