// Code generated by "stringer -type=Mutation"; DO NOT EDIT.

package flow

import "strconv"

const _Mutation_name = "IncrDecrCachedRefresh"

var _Mutation_index = [...]uint8{0, 4, 8, 14, 21}

func (i Mutation) String() string {
	if i < 0 || i >= Mutation(len(_Mutation_index)-1) {
		return "Mutation(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Mutation_name[_Mutation_index[i]:_Mutation_index[i+1]]
}
