// Copyright 2017 GRAIL, Inc. All rights reserved.
// Use of this source code is governed by the Apache 2.0
// license that can be found in the LICENSE file.

// Code generated by "stringer -type=Op"; DO NOT EDIT

package flow

import "fmt"

const _Op_name = "OpExecOpInternOpExternOpGroupbyOpMapOpCollectOpMergeOpValOpPullupOpKOpCoerceOpRequirementsmaxOp"

var _Op_index = [...]uint8{0, 6, 14, 22, 31, 36, 45, 52, 57, 65, 68, 76, 90, 95}

func (i Op) DigestString() string {
	i -= 1
	if i < 0 || i >= Op(len(_Op_index)-1) {
		return fmt.Sprintf("Op(%d)", i+1)
	}
	return _Op_name[_Op_index[i]:_Op_index[i+1]]
}
