// Code generated by "stringer -type=State"; DO NOT EDIT.

package flow

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Init-0]
	_ = x[NeedLookup-1]
	_ = x[Lookup-2]
	_ = x[TODO-3]
	_ = x[NeedTransfer-4]
	_ = x[Transfer-5]
	_ = x[Ready-6]
	_ = x[NeedSubmit-7]
	_ = x[Running-8]
	_ = x[Execing-9]
	_ = x[Done-10]
	_ = x[Max-11]
}

const _State_name = "InitNeedLookupLookupTODONeedTransferTransferReadyNeedSubmitRunningExecingDoneMax"

var _State_index = [...]uint8{0, 4, 14, 20, 24, 36, 44, 49, 59, 66, 73, 77, 80}

func (i State) String() string {
	if i < 0 || i >= State(len(_State_index)-1) {
		return "State(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _State_name[_State_index[i]:_State_index[i+1]]
}
