// Code generated by "stringer -type=ConstLevel"; DO NOT EDIT

package types

import "fmt"

const _ConstLevel_name = "NotConstCanConstConst"

var _ConstLevel_index = [...]uint8{0, 8, 16, 21}

func (i ConstLevel) String() string {
	i -= -1
	if i < 0 || i >= ConstLevel(len(_ConstLevel_index)-1) {
		return fmt.Sprintf("ConstLevel(%d)", i+-1)
	}
	return _ConstLevel_name[_ConstLevel_index[i]:_ConstLevel_index[i+1]]
}
