// Code generated by "stringer -type=Kind"; DO NOT EDIT.

package trace

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Run-0]
	_ = x[Exec-1]
	_ = x[Cache-2]
	_ = x[Transfer-3]
	_ = x[AllocReq-4]
	_ = x[AllocLifespan-5]
}

const _Kind_name = "RunExecCacheTransferAllocReqAllocLifespan"

var _Kind_index = [...]uint8{0, 3, 7, 12, 20, 28, 41}

func (i Kind) String() string {
	if i < 0 || i >= Kind(len(_Kind_index)-1) {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
