// Copyright 2018 GRAIL, Inc. All rights reserved.
// Use of this source code is governed by the Apache 2.0
// license that can be found in the LICENSE file.

// This file is automatically generated by releasereflow. Do not edit!

package main

const (
	version   = "reflow0.5.3"
	reflowlet = "grailbio/reflowlet:1510608135"
)
