// Code generated by goyacc reflow.y. DO NOT EDIT.

//line reflow.y:2
package syntax

import __yyfmt__ "fmt"

//line reflow.y:2

import (
	"fmt"

	"github.com/grailbio/reflow/internal/scanner"
	"github.com/grailbio/reflow/types"
)

type posIdents struct {
	pos      scanner.Position
	idents   []string
	comments []string
}

type typearg struct {
	t1, t2 *types.T
}

//line reflow.y:23
type yySymType struct {
	yys int
	pos struct {
		scanner.Position
		comment string
	}
	expr       *Expr
	exprlist   []*Expr
	exprfield  *FieldExpr
	exprfields []*FieldExpr
	exprmap    map[*Expr]*Expr

	comprclauses []*ComprClause
	comprclause  *ComprClause

	typ         *types.T
	typlist     []*types.T
	typfield    *types.Field
	typfields   []*types.Field
	decl        *Decl
	decllist    []*Decl
	pat         *Pat
	patlist     []*Pat
	caseclause  *CaseClause
	caseclauses []*CaseClause
	tok         int
	template    *Template

	structpat struct {
		field string
		pat   *Pat
	}

	structpats []struct {
		field string
		pat   *Pat
	}

	listpats struct {
		list []*Pat
		tail *Pat
	}

	typearg  typearg
	typeargs []typearg

	module *ModuleImpl

	str string

	idents    []string
	posidents posIdents
}

const tokIdent = 57346
const tokExpr = 57347
const tokInt = 57348
const tokString = 57349
const tokBool = 57350
const tokFloat = 57351
const tokTemplate = 57352
const tokFile = 57353
const tokDir = 57354
const tokStruct = 57355
const tokModule = 57356
const tokExec = 57357
const tokAs = 57358
const tokAt = 57359
const tokVal = 57360
const tokFunc = 57361
const tokAssign = 57362
const tokArrow = 57363
const tokLeftArrow = 57364
const tokIf = 57365
const tokElse = 57366
const tokSwitch = 57367
const tokCase = 57368
const tokMake = 57369
const tokLen = 57370
const tokPanic = 57371
const tokDelay = 57372
const tokTrace = 57373
const tokMap = 57374
const tokList = 57375
const tokZip = 57376
const tokUnzip = 57377
const tokFlatten = 57378
const tokStartModule = 57379
const tokStartDecls = 57380
const tokStartExpr = 57381
const tokStartType = 57382
const tokStartPat = 57383
const tokKeyspace = 57384
const tokParam = 57385
const tokEllipsis = 57386
const tokReserved = 57387
const tokRequires = 57388
const tokRange = 57389
const tokType = 57390
const tokOrOr = 57391
const tokAndAnd = 57392
const tokLE = 57393
const tokGE = 57394
const tokNE = 57395
const tokEqEq = 57396
const tokLSH = 57397
const tokRSH = 57398
const tokSquiggleArrow = 57399
const tokEOF = 57400
const tokError = 57401
const first = 57402
const unary = 57403
const apply = 57404
const deref = 57405

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"tokIdent",
	"tokExpr",
	"tokInt",
	"tokString",
	"tokBool",
	"tokFloat",
	"tokTemplate",
	"tokFile",
	"tokDir",
	"tokStruct",
	"tokModule",
	"tokExec",
	"tokAs",
	"tokAt",
	"tokVal",
	"tokFunc",
	"tokAssign",
	"tokArrow",
	"tokLeftArrow",
	"tokIf",
	"tokElse",
	"tokSwitch",
	"tokCase",
	"tokMake",
	"tokLen",
	"tokPanic",
	"tokDelay",
	"tokTrace",
	"tokMap",
	"tokList",
	"tokZip",
	"tokUnzip",
	"tokFlatten",
	"tokStartModule",
	"tokStartDecls",
	"tokStartExpr",
	"tokStartType",
	"tokStartPat",
	"tokKeyspace",
	"tokParam",
	"tokEllipsis",
	"tokReserved",
	"tokRequires",
	"tokRange",
	"tokType",
	"'{'",
	"'('",
	"'['",
	"tokOrOr",
	"tokAndAnd",
	"tokLE",
	"tokGE",
	"tokNE",
	"tokEqEq",
	"tokLSH",
	"tokRSH",
	"tokSquiggleArrow",
	"'<'",
	"'>'",
	"'+'",
	"'-'",
	"'|'",
	"'^'",
	"'*'",
	"'/'",
	"'%'",
	"'&'",
	"'_'",
	"'!'",
	"tokEOF",
	"tokError",
	"first",
	"unary",
	"'.'",
	"']'",
	"')'",
	"apply",
	"deref",
	"':'",
	"'}'",
	"','",
	"';'",
	"'='",
}
var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line yacctab:1
var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 62,
	85, 167,
	-2, 47,
}

const yyPrivate = 57344

const yyLast = 1408

var yyAct = [...]int{

	11, 102, 182, 248, 262, 66, 134, 359, 181, 176,
	273, 178, 41, 65, 94, 235, 95, 96, 133, 143,
	187, 266, 180, 103, 131, 100, 127, 109, 104, 381,
	342, 10, 307, 263, 92, 91, 360, 368, 139, 261,
	328, 122, 88, 89, 179, 55, 329, 82, 83, 293,
	219, 84, 85, 86, 87, 54, 125, 42, 44, 45,
	43, 93, 46, 47, 345, 51, 323, 254, 253, 252,
	53, 234, 255, 252, 353, 155, 156, 157, 158, 159,
	160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
	170, 171, 172, 174, 145, 126, 231, 232, 218, 219,
	50, 52, 49, 190, 193, 189, 324, 336, 151, 148,
	320, 202, 203, 204, 205, 206, 207, 208, 209, 210,
	211, 212, 213, 219, 247, 230, 228, 195, 224, 198,
	199, 196, 188, 374, 152, 221, 321, 371, 258, 216,
	378, 225, 54, 217, 42, 44, 45, 43, 65, 46,
	47, 194, 51, 242, 233, 238, 376, 53, 241, 355,
	226, 244, 347, 309, 334, 92, 91, 74, 75, 78,
	79, 80, 81, 88, 89, 222, 76, 77, 82, 83,
	295, 251, 84, 85, 86, 87, 257, 50, 52, 49,
	227, 223, 93, 267, 246, 264, 194, 268, 92, 91,
	271, 267, 276, 361, 92, 91, 88, 89, 357, 250,
	337, 229, 259, 197, 124, 84, 85, 86, 87, 70,
	270, 243, 220, 136, 290, 93, 123, 269, 56, 61,
	341, 93, 68, 69, 71, 265, 138, 153, 238, 274,
	312, 306, 239, 294, 302, 135, 291, 275, 310, 121,
	120, 313, 299, 65, 119, 308, 118, 117, 315, 311,
	317, 316, 305, 72, 116, 56, 177, 296, 325, 296,
	115, 114, 300, 60, 58, 59, 331, 319, 318, 183,
	56, 332, 113, 97, 236, 333, 70, 322, 64, 112,
	111, 326, 68, 69, 71, 57, 141, 110, 99, 68,
	69, 71, 338, 98, 343, 298, 97, 130, 346, 149,
	60, 58, 59, 348, 147, 350, 9, 340, 349, 249,
	105, 356, 330, 72, 358, 60, 58, 59, 362, 351,
	72, 364, 57, 68, 69, 71, 70, 339, 152, 354,
	363, 352, 184, 369, 63, 344, 129, 57, 144, 68,
	69, 71, 375, 370, 372, 292, 260, 215, 373, 175,
	154, 153, 316, 1, 72, 140, 377, 137, 274, 142,
	297, 146, 380, 62, 7, 367, 379, 382, 256, 384,
	386, 104, 387, 173, 101, 237, 128, 389, 388, 189,
	18, 17, 29, 132, 48, 30, 272, 19, 20, 108,
	106, 22, 335, 289, 385, 21, 383, 14, 27, 13,
	8, 40, 12, 23, 28, 38, 37, 39, 34, 36,
	31, 32, 33, 67, 2, 3, 4, 5, 6, 150,
	301, 0, 0, 35, 0, 25, 24, 26, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	16, 0, 54, 0, 42, 44, 45, 43, 15, 46,
	47, 0, 51, 0, 0, 0, 0, 53, 107, 92,
	91, 74, 75, 78, 79, 80, 81, 88, 89, 90,
	76, 77, 82, 83, 0, 0, 84, 85, 86, 87,
	0, 0, 0, 0, 0, 0, 93, 50, 52, 49,
	0, 0, 0, 0, 360, 92, 91, 74, 75, 78,
	79, 80, 81, 88, 89, 90, 76, 77, 82, 83,
	0, 0, 84, 85, 86, 87, 0, 0, 0, 0,
	0, 0, 93, 0, 240, 0, 0, 0, 0, 0,
	263, 92, 91, 74, 75, 78, 79, 80, 81, 88,
	89, 90, 76, 77, 82, 83, 0, 0, 84, 85,
	86, 87, 0, 0, 0, 0, 0, 0, 93, 0,
	186, 0, 0, 0, 0, 185, 92, 91, 74, 75,
	78, 79, 80, 81, 88, 89, 90, 76, 77, 82,
	83, 0, 0, 84, 85, 86, 87, 0, 0, 0,
	0, 0, 0, 93, 0, 0, 0, 0, 0, 0,
	284, 92, 91, 74, 75, 78, 79, 80, 81, 88,
	89, 90, 76, 77, 82, 83, 0, 0, 84, 85,
	86, 87, 0, 0, 0, 0, 0, 0, 93, 0,
	0, 0, 0, 0, 0, 280, 92, 91, 74, 75,
	78, 79, 80, 81, 88, 89, 90, 76, 77, 82,
	83, 200, 0, 84, 85, 86, 87, 0, 0, 0,
	0, 0, 0, 93, 0, 0, 0, 0, 201, 92,
	91, 74, 75, 78, 79, 80, 81, 88, 89, 90,
	76, 77, 82, 83, 0, 0, 84, 85, 86, 87,
	0, 0, 191, 17, 29, 0, 93, 30, 0, 19,
	20, 327, 0, 22, 0, 68, 69, 192, 0, 0,
	0, 13, 0, 40, 0, 23, 28, 38, 37, 39,
	34, 36, 31, 32, 33, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 35, 72, 25, 24, 26,
	54, 0, 42, 44, 45, 43, 0, 46, 47, 0,
	51, 0, 16, 0, 0, 53, 0, 314, 0, 0,
	15, 92, 91, 74, 75, 78, 79, 80, 81, 88,
	89, 90, 76, 77, 82, 83, 0, 0, 84, 85,
	86, 87, 0, 0, 0, 50, 52, 49, 93, 0,
	366, 92, 91, 74, 75, 78, 79, 80, 81, 88,
	89, 90, 76, 77, 82, 83, 0, 0, 84, 85,
	86, 87, 0, 0, 0, 0, 0, 0, 93, 54,
	365, 42, 44, 45, 43, 0, 46, 47, 0, 51,
	0, 0, 0, 0, 53, 0, 0, 0, 0, 0,
	92, 91, 74, 75, 78, 79, 80, 81, 88, 89,
	90, 76, 77, 82, 83, 0, 0, 84, 85, 86,
	87, 0, 0, 0, 50, 52, 49, 93, 0, 288,
	0, 92, 91, 74, 75, 78, 79, 80, 81, 88,
	89, 90, 76, 77, 82, 83, 0, 0, 84, 85,
	86, 87, 0, 0, 0, 0, 0, 0, 93, 304,
	287, 303, 92, 91, 74, 75, 78, 79, 80, 81,
	88, 89, 90, 76, 77, 82, 83, 0, 0, 84,
	85, 86, 87, 0, 0, 0, 0, 0, 0, 93,
	0, 286, 92, 91, 74, 75, 78, 79, 80, 81,
	88, 89, 90, 76, 77, 82, 83, 0, 0, 84,
	85, 86, 87, 0, 0, 0, 0, 0, 0, 93,
	0, 285, 92, 91, 74, 75, 78, 79, 80, 81,
	88, 89, 90, 76, 77, 82, 83, 0, 0, 84,
	85, 86, 87, 0, 0, 0, 0, 0, 0, 93,
	0, 283, 92, 91, 74, 75, 78, 79, 80, 81,
	88, 89, 90, 76, 77, 82, 83, 0, 0, 84,
	85, 86, 87, 0, 0, 0, 0, 0, 0, 93,
	0, 282, 92, 91, 74, 75, 78, 79, 80, 81,
	88, 89, 90, 76, 77, 82, 83, 0, 0, 84,
	85, 86, 87, 0, 0, 0, 0, 0, 0, 93,
	0, 281, 92, 91, 74, 75, 78, 79, 80, 81,
	88, 89, 90, 76, 77, 82, 83, 0, 0, 84,
	85, 86, 87, 0, 0, 0, 0, 0, 0, 93,
	0, 279, 92, 91, 74, 75, 78, 79, 80, 81,
	88, 89, 90, 76, 77, 82, 83, 0, 0, 84,
	85, 86, 87, 0, 0, 0, 0, 0, 0, 93,
	0, 278, 92, 91, 74, 75, 78, 79, 80, 81,
	88, 89, 90, 76, 77, 82, 83, 0, 0, 84,
	85, 86, 87, 0, 0, 0, 0, 0, 0, 93,
	0, 277, 92, 91, 74, 75, 78, 79, 80, 81,
	88, 89, 90, 76, 77, 82, 83, 0, 0, 84,
	85, 86, 87, 0, 0, 0, 18, 17, 29, 93,
	245, 30, 0, 19, 20, 0, 0, 22, 0, 0,
	0, 21, 0, 0, 0, 13, 0, 40, 0, 23,
	28, 38, 37, 39, 34, 36, 31, 32, 33, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 35,
	0, 25, 24, 26, 54, 0, 42, 44, 45, 43,
	0, 46, 47, 0, 51, 0, 16, 0, 0, 53,
	0, 0, 0, 0, 15, 177, 92, 91, 74, 75,
	78, 79, 80, 81, 88, 89, 90, 76, 77, 82,
	83, 0, 0, 84, 85, 86, 87, 0, 0, 50,
	52, 49, 0, 93, 214, 92, 91, 74, 75, 78,
	79, 80, 81, 88, 89, 90, 76, 77, 82, 83,
	0, 0, 84, 85, 86, 87, 0, 0, 0, 0,
	0, 0, 93, 92, 91, 74, 75, 78, 79, 80,
	81, 88, 89, 90, 76, 77, 82, 83, 0, 0,
	84, 85, 86, 87, 0, 0, 73, 0, 0, 0,
	93, 92, 91, 74, 75, 78, 79, 80, 81, 88,
	89, 90, 76, 77, 82, 83, 0, 0, 84, 85,
	86, 87, 0, 0, 0, 0, 92, 91, 93, 75,
	78, 79, 80, 81, 88, 89, 0, 76, 77, 82,
	83, 0, 0, 84, 85, 86, 87, 0, 0, 0,
	92, 91, 0, 93, 78, 79, 80, 81, 88, 89,
	0, 76, 77, 82, 83, 0, 0, 84, 85, 86,
	87, 0, 0, 0, 0, 0, 0, 93,
}
var yyPact = [...]int{

	387, -1000, 274, -1000, 1172, 1220, 276, 156, -1000, 339,
	215, 1253, -1000, 1172, -1000, 1172, 1172, -1000, -1000, -1000,
	-1000, 256, 253, 248, 1172, 316, 386, -1000, 247, 240,
	239, 232, 221, 220, 214, 207, 206, 204, 200, 199,
	1172, 153, -1000, -1000, -1000, -1000, -1000, -1000, 137, 1220,
	342, 258, 1220, 195, -1000, 150, -1000, -1000, 276, 276,
	344, -1000, 271, -1000, -1000, 24, -1000, -1000, 263, 276,
	318, 357, 356, -1000, 1172, 1172, 1172, 1172, 1172, 1172,
	1172, 1172, 1172, 1172, 1172, 1172, 1172, 1172, 1172, 1172,
	1172, 1172, 1172, 355, 1196, 154, 154, 342, 275, 337,
	491, 48, 698, -1000, 19, 114, 47, 135, 46, 596,
	1172, 1172, 1172, 1172, 1172, 1172, 1172, 1172, 1172, 1172,
	1172, 1172, 1225, -1000, 353, 61, 15, -1000, 138, -1000,
	342, 112, 44, -1000, 1220, 1220, -1000, 111, 42, -1000,
	133, 41, 13, -1000, 72, 282, -14, 234, -1000, 192,
	-1000, 448, 1172, 171, 1220, 1306, 1330, -16, -16, -16,
	-16, -16, -16, 148, 148, 154, 154, 154, 154, 154,
	154, 115, 1102, 40, 1281, -1000, 295, -1000, 102, 39,
	-11, -1000, -1000, 318, -12, 1172, -1000, 55, 352, -46,
	455, 318, 233, -1000, 1172, 157, 1172, -1000, 149, 1172,
	224, 1172, 1072, 1042, 1012, 561, 982, 952, 922, 526,
	892, 862, 831, 800, -1000, -1000, -1000, 1220, -1000, 342,
	351, -1000, -34, -1000, 1220, -1000, 101, -1000, 276, -1000,
	261, -1000, 344, 276, -1000, -1000, -1000, 825, -1000, 275,
	1172, -54, 1281, 342, -1000, -1000, 84, 1172, -1000, 217,
	698, 746, 275, 1220, -1000, 275, 26, 1281, -1000, -1000,
	69, -1000, 53, -1000, 1281, -1000, 22, 1172, 1281, -1000,
	22, 629, -38, -1000, 300, 1172, 1281, -1000, -1000, -1000,
	1172, -1000, -1000, -1000, 1172, -1000, -1000, -1000, -1000, 81,
	132, -1000, -1000, -1000, -1000, 1220, -1000, -1000, 276, -1000,
	-1000, 151, -56, 1172, 341, -15, 1281, 1172, 83, -1000,
	1281, -1000, 1172, 455, 1172, 308, -1000, 331, -10, 80,
	1172, -1000, 130, 1172, -1000, 419, 125, 1172, -1000, 224,
	1172, 1281, 751, 721, -1000, -1000, 276, -1000, -1000, -1000,
	-48, -1000, 1172, 1281, -1000, -49, 1281, 51, 1196, 50,
	1281, 1172, -1000, 275, 77, -1000, 1281, -1000, 419, -1000,
	-1000, -1000, 1281, -1000, 1281, -1000, -1000, 58, -1000, 1281,
	332, 1172, -57, 295, -1000, 1281, -1000, -1000, 698, -1000,
	1281, 1172, -1000, -52, 1281, -1000, 698, 1281, -1000, 1281,
}
var yyPgo = [...]int{

	0, 31, 1, 22, 15, 430, 429, 5, 423, 2,
	8, 0, 412, 410, 408, 9, 3, 407, 406, 404,
	403, 402, 400, 21, 399, 396, 10, 394, 6, 18,
	393, 24, 44, 26, 11, 386, 385, 23, 384, 383,
	378, 374, 373, 371, 38, 370, 19, 369, 367, 236,
	365, 363, 7, 20, 4,
}
var yyR1 = [...]int{

	0, 51, 51, 51, 51, 51, 27, 27, 28, 28,
	28, 28, 28, 28, 28, 28, 28, 28, 28, 28,
	28, 35, 35, 33, 32, 32, 29, 29, 30, 30,
	31, 44, 44, 44, 44, 44, 50, 50, 45, 45,
	48, 49, 49, 47, 47, 46, 46, 1, 1, 2,
	2, 3, 3, 3, 10, 10, 5, 5, 9, 9,
	7, 7, 7, 7, 7, 8, 6, 6, 4, 4,
	4, 36, 36, 11, 11, 11, 11, 11, 11, 11,
	11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
	11, 11, 11, 11, 11, 11, 11, 11, 16, 16,
	12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
	12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
	12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
	12, 14, 15, 17, 20, 20, 21, 18, 18, 19,
	25, 25, 26, 26, 54, 54, 38, 38, 37, 37,
	22, 22, 22, 23, 23, 40, 40, 39, 39, 24,
	24, 34, 41, 13, 13, 42, 42, 43, 43, 43,
	53, 53, 52, 52,
}
var yyR2 = [...]int{

	0, 3, 3, 3, 3, 3, 1, 3, 1, 1,
	1, 1, 1, 1, 1, 3, 5, 3, 4, 3,
	5, 1, 3, 2, 1, 3, 1, 2, 1, 3,
	1, 1, 1, 3, 3, 3, 1, 3, 1, 2,
	1, 1, 3, 1, 3, 1, 3, 0, 3, 2,
	3, 0, 1, 3, 1, 1, 0, 3, 1, 1,
	7, 2, 3, 7, 8, 3, 3, 4, 2, 3,
	4, 1, 3, 1, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 4, 1, 4, 5, 3, 2, 2, 2, 5,
	1, 1, 1, 1, 6, 7, 6, 4, 7, 6,
	4, 4, 6, 3, 4, 6, 5, 3, 1, 4,
	4, 4, 6, 4, 4, 4, 6, 4, 4, 4,
	4, 5, 5, 5, 0, 2, 5, 1, 1, 2,
	1, 3, 3, 2, 0, 1, 1, 3, 1, 3,
	0, 1, 3, 3, 4, 1, 3, 1, 3, 3,
	5, 1, 3, 0, 2, 0, 3, 0, 2, 4,
	0, 1, 0, 1,
}
var yyChk = [...]int{

	-1000, -51, 37, 38, 39, 40, 41, -41, -13, 42,
	-1, -11, -12, 23, -17, 72, 64, 5, 4, 11,
	12, 19, 15, 27, 50, 49, 51, -14, 28, 6,
	9, 34, 35, 36, 32, 47, 33, 30, 29, 31,
	25, -28, 6, 9, 7, 8, 11, 12, -27, 51,
	49, 14, 50, 19, 4, -44, 4, 71, 50, 51,
	49, 73, -42, 5, 73, -9, -7, -8, 17, 18,
	4, 19, 48, 73, 52, 53, 61, 62, 54, 55,
	56, 57, 63, 64, 67, 68, 69, 70, 58, 59,
	60, 51, 50, 77, -11, -11, -11, 50, 50, 50,
	-11, -38, -2, -37, -9, 4, -22, 82, -24, -11,
	50, 50, 50, 50, 50, 50, 50, 50, 50, 50,
	50, 50, -11, 73, 77, -28, -32, -33, -35, 4,
	49, -31, -30, -29, -28, 50, 73, -48, -49, -44,
	-50, -49, -47, -46, 4, -1, -43, 43, 85, 46,
	-6, -44, 20, 4, 4, -11, -11, -11, -11, -11,
	-11, -11, -11, -11, -11, -11, -11, -11, -11, -11,
	-11, -11, -11, -39, -11, 4, -15, 49, -34, -32,
	-3, -10, -9, 4, 5, 84, 79, -53, 84, -9,
	-11, 4, 19, 85, 82, -53, 84, 78, -53, 84,
	65, 82, -11, -11, -11, -11, -11, -11, -11, -11,
	-11, -11, -11, -11, 49, 4, 78, 82, 83, 84,
	84, -28, -32, 79, 84, -28, -31, 79, 84, 78,
	84, 83, 84, 82, 85, -4, 50, -36, 4, 50,
	86, -28, -11, 50, -28, 78, -53, 84, -16, 24,
	-1, 79, 84, 79, 79, 84, -40, -11, 83, -37,
	4, 85, -54, 85, -11, 78, -23, 44, -11, 78,
	-23, -11, -25, -26, -44, 23, -11, 79, 79, 79,
	84, 79, 79, 79, 84, 79, 79, 79, 79, -20,
	-28, -33, 4, 83, -29, 79, -44, -45, 44, -46,
	-44, -5, -28, 86, 84, -3, -11, 86, -34, 79,
	-11, -15, 23, -11, 21, -28, -10, -28, -3, -53,
	84, 83, -53, 44, 84, -11, -53, 82, 78, 84,
	22, -11, -11, -11, 83, -21, 26, 78, -28, -44,
	-4, 79, 86, -11, 4, 79, -11, 79, -11, -54,
	-11, 21, 10, 84, -53, 79, -11, 78, -11, -52,
	85, 78, -11, -26, -11, 79, 79, -44, 85, -11,
	-52, 86, -28, -15, 83, -11, 79, -52, 82, -7,
	-11, 86, -16, -18, -11, -19, -2, -11, -54, -11,
}
var yyDef = [...]int{

	0, -2, 163, 47, 0, 0, 0, 0, 165, 0,
	0, 0, 73, 0, 92, 0, 0, 100, 101, 102,
	103, 0, 0, 0, 0, 0, 150, 118, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 8, 9, 10, 11, 12, 13, 14, 0,
	0, 0, 0, 0, 6, 0, 31, 32, 0, 0,
	0, 1, -2, 164, 2, 0, 58, 59, 0, 0,
	0, 0, 0, 3, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 96, 97, 0, 51, 0,
	0, 170, 0, 146, 0, 148, 170, 0, 170, 151,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 4, 0, 0, 0, 24, 0, 21,
	0, 0, 30, 28, 26, 0, 5, 0, 40, 41,
	0, 36, 0, 43, 45, 162, 0, 0, 48, 0,
	61, 0, 0, 0, 0, 74, 75, 76, 77, 78,
	79, 80, 81, 82, 83, 84, 85, 86, 87, 88,
	89, 90, 0, 170, 157, 95, 0, 47, 0, 161,
	0, 52, 54, 55, 0, 0, 117, 0, 171, 0,
	144, 101, 0, 49, 0, 0, 171, 113, 0, 171,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 134, 7, 15, 0, 17, 0,
	0, 23, 0, 19, 0, 27, 0, 33, 0, 34,
	0, 35, 0, 0, 166, 168, 56, 0, 71, 51,
	0, 0, 62, 0, 65, 93, 0, 171, 91, 0,
	0, 0, 0, 0, 107, 51, 170, 155, 110, 147,
	148, 50, 0, 145, 149, 111, 170, 0, 152, 114,
	170, 0, 0, 140, 0, 0, 159, 119, 120, 121,
	0, 123, 124, 125, 0, 127, 128, 129, 130, 0,
	0, 25, 22, 18, 29, 0, 42, 37, 38, 44,
	46, 0, 68, 0, 0, 0, 66, 0, 0, 94,
	158, 98, 0, 144, 0, 0, 53, 0, 170, 0,
	171, 131, 0, 0, 171, 172, 0, 0, 116, 0,
	0, 143, 0, 0, 133, 135, 0, 16, 20, 39,
	0, 169, 0, 69, 72, 172, 67, 0, 0, 0,
	104, 0, 106, 171, 0, 109, 156, 112, 172, 153,
	173, 115, 160, 141, 142, 122, 126, 0, 57, 70,
	0, 0, 0, 0, 132, 105, 108, 154, 0, 60,
	63, 0, 99, 144, 137, 138, 0, 64, 136, 139,
}
var yyTok1 = [...]int{

	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 72, 3, 3, 3, 69, 70, 3,
	50, 79, 67, 63, 84, 64, 77, 68, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 82, 85,
	61, 86, 62, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 51, 3, 78, 66, 71, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 49, 65, 83,
}
var yyTok2 = [...]int{

	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 52, 53, 54,
	55, 56, 57, 58, 59, 60, 73, 74, 75, 76,
	80, 81,
}
var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:138
		{
			yylex.(*Parser).Module = yyDollar[2].module
			return 0
		}
	case 2:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:143
		{
			yylex.(*Parser).Decls = yyDollar[2].decllist
			return 0
		}
	case 3:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:148
		{
			yylex.(*Parser).Expr = yyDollar[2].expr
			return 0
		}
	case 4:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:153
		{
			yylex.(*Parser).Type = yyDollar[2].typ
			return 0
		}
	case 5:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:158
		{
			yylex.(*Parser).Pat = yyDollar[2].pat
			return 0
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
//line reflow.y:169
		{
			yyVAL.idents = []string{yyDollar[1].expr.Ident}
		}
	case 7:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:171
		{
			yyVAL.idents = append(yyDollar[1].idents, yyDollar[3].expr.Ident)
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
//line reflow.y:174
		{
			yyVAL.typ = types.Int
		}
	case 9:
		yyDollar = yyS[yypt-1 : yypt+1]
//line reflow.y:175
		{
			yyVAL.typ = types.Float
		}
	case 10:
		yyDollar = yyS[yypt-1 : yypt+1]
//line reflow.y:176
		{
			yyVAL.typ = types.String
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
//line reflow.y:177
		{
			yyVAL.typ = types.Bool
		}
	case 12:
		yyDollar = yyS[yypt-1 : yypt+1]
//line reflow.y:178
		{
			yyVAL.typ = types.File
		}
	case 13:
		yyDollar = yyS[yypt-1 : yypt+1]
//line reflow.y:179
		{
			yyVAL.typ = types.Dir
		}
	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
//line reflow.y:180
		{
			yyVAL.typ = types.Ref(yyDollar[1].idents...)
		}
	case 15:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:181
		{
			yyVAL.typ = types.List(yyDollar[2].typ)
		}
	case 16:
		yyDollar = yyS[yypt-5 : yypt+1]
//line reflow.y:183
		{
			yyVAL.typ = types.Map(yyDollar[2].typ, yyDollar[4].typ)
		}
	case 17:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:185
		{
			yyVAL.typ = types.Struct(yyDollar[2].typfields...)
		}
	case 18:
		yyDollar = yyS[yypt-4 : yypt+1]
//line reflow.y:187
		{
			yyVAL.typ = types.Module(yyDollar[3].typfields, nil)
		}
	case 19:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:189
		{
			switch len(yyDollar[2].typfields) {
			// "()" is unit
			case 0:
				yyVAL.typ = types.Unit
				// "(type)" and "(name type)" get collapsed with
			// (optional) label
			case 1:
				yyVAL.typ = types.Labeled(yyDollar[2].typfields[0].Name, yyDollar[2].typfields[0].T)
				// a regular tuple must have at least two members
			default:
				yyVAL.typ = types.Tuple(yyDollar[2].typfields...)
			}
		}
	case 20:
		yyDollar = yyS[yypt-5 : yypt+1]
//line reflow.y:201
		{
			yyVAL.typ = types.Func(yyDollar[5].typ, yyDollar[3].typfields...)
		}
	case 21:
		yyDollar = yyS[yypt-1 : yypt+1]
//line reflow.y:205
		{
			yyVAL.idents = []string{yyDollar[1].expr.Ident}
		}
	case 22:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:207
		{
			yyVAL.idents = append(yyDollar[1].idents, yyDollar[3].expr.Ident)
		}
	case 23:
		yyDollar = yyS[yypt-2 : yypt+1]
//line reflow.y:211
		{
			for _, name := range yyDollar[1].idents {
				yyVAL.typfields = append(yyVAL.typfields, &types.Field{Name: name, T: yyDollar[2].typ})
			}
		}
	case 24:
		yyDollar = yyS[yypt-1 : yypt+1]
//line reflow.y:219
		{
			yyVAL.typfields = yyDollar[1].typfields
		}
	case 25:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:221
		{
			yyVAL.typfields = append(yyDollar[1].typfields, yyDollar[3].typfields...)
		}
	case 26:
		yyDollar = yyS[yypt-1 : yypt+1]
//line reflow.y:225
		{
			yyVAL.typearg = typearg{yyDollar[1].typ, nil}
		}
	case 27:
		yyDollar = yyS[yypt-2 : yypt+1]
//line reflow.y:227
		{
			yyVAL.typearg = typearg{yyDollar[1].typ, yyDollar[2].typ}
		}
	case 28:
		yyDollar = yyS[yypt-1 : yypt+1]
//line reflow.y:231
		{
			yyVAL.typeargs = []typearg{yyDollar[1].typearg}
		}
	case 29:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:233
		{
			yyVAL.typeargs = append(yyDollar[1].typeargs, yyDollar[3].typearg)
		}
	case 30:
		yyDollar = yyS[yypt-1 : yypt+1]
//line reflow.y:242
		{
			var (
				fields []*types.Field
				group  []*types.T
			)
			for _, arg := range yyDollar[1].typeargs {
				group = append(group, arg.t1)
				if arg.t2 != nil { // x, y, z t2
					// We have a group: check that they are all
					// idents, and convert them accordingly.
					for _, id := range group {
						if id.Kind != types.RefKind {
							yylex.Error(fmt.Sprintf("expected identifier, found %s", id))
							goto Fail
						}
						if len(id.Path) != 1 {
							yylex.Error(fmt.Sprintf("non-simple argument name"))
							goto Fail
						}
						fields = append(fields, &types.Field{Name: id.Path[0], T: arg.t2})
					}
					group = nil
				}
			}
			if len(group) > 0 {
				if len(fields) > 0 {
					yylex.Error("cannot mix named and unnamed arguments")
					goto Fail
				}
				// Only unnamed arguments: they are all types.
				for _, t := range group {
					fields = append(fields, &types.Field{T: t})
				}
			}
			yyVAL.typfields = fields
		Fail:
		}
	case 31:
		yyDollar = yyS[yypt-1 : yypt+1]
//line reflow.y:284
		{
			yyVAL.pat = &Pat{Position: yyDollar[1].expr.Position, Kind: PatIdent, Ident: yyDollar[1].expr.Ident}
		}
	case 32:
		yyDollar = yyS[yypt-1 : yypt+1]
//line reflow.y:286
		{
			yyVAL.pat = &Pat{Position: yyDollar[1].pos.Position, Kind: PatIgnore}
		}
	case 33:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:288
		{
			yyVAL.pat = &Pat{Position: yyDollar[1].pos.Position, Kind: PatTuple, List: yyDollar[2].patlist}
		}
	case 34:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:290
		{
			yyVAL.pat = &Pat{Position: yyDollar[1].pos.Position, Kind: PatList, List: yyDollar[2].listpats.list, Tail: yyDollar[2].listpats.tail}
		}
	case 35:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:292
		{
			yyVAL.pat = &Pat{Position: yyDollar[1].pos.Position, Kind: PatStruct, Fields: make([]PatField, len(yyDollar[2].structpats))}
			for i, p := range yyDollar[2].structpats {
				yyVAL.pat.Fields[i] = PatField{p.field, p.pat}
			}
		}
	case 36:
		yyDollar = yyS[yypt-1 : yypt+1]
//line reflow.y:301
		{
			yyVAL.listpats = struct {
				list []*Pat
				tail *Pat
			}{
				list: yyDollar[1].patlist,
			}
		}
	case 37:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:308
		{
			yyVAL.listpats = struct {
				list []*Pat
				tail *Pat
			}{
				list: yyDollar[1].patlist,
				tail: yyDollar[3].pat,
			}
		}
	case 38:
		yyDollar = yyS[yypt-1 : yypt+1]
//line reflow.y:318
		{
			yyVAL.pat = &Pat{Position: yyDollar[1].pos.Position, Kind: PatIgnore}
		}
	case 39:
		yyDollar = yyS[yypt-2 : yypt+1]
//line reflow.y:320
		{
			yyVAL.pat = yyDollar[2].pat
		}
	case 41:
		yyDollar = yyS[yypt-1 : yypt+1]
//line reflow.y:327
		{
			yyVAL.patlist = []*Pat{yyDollar[1].pat}
		}
	case 42:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:329
		{
			yyVAL.patlist = append(yyDollar[1].patlist, yyDollar[3].pat)
		}
	case 43:
		yyDollar = yyS[yypt-1 : yypt+1]
//line reflow.y:333
		{
			yyVAL.structpats = []struct {
				field string
				pat   *Pat
			}{yyDollar[1].structpat}
		}
	case 44:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:338
		{
			yyVAL.structpats = append(yyDollar[1].structpats, yyDollar[3].structpat)
		}
	case 45:
		yyDollar = yyS[yypt-1 : yypt+1]
//line reflow.y:342
		{
			yyVAL.structpat = struct {
				field string
				pat   *Pat
			}{yyDollar[1].expr.Ident, &Pat{Kind: PatIdent, Ident: yyDollar[1].expr.Ident}}
		}
	case 46:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:347
		{
			yyVAL.structpat = struct {
				field string
				pat   *Pat
			}{yyDollar[1].expr.Ident, yyDollar[3].pat}
		}
	case 47:
		yyDollar = yyS[yypt-0 : yypt+1]
//line reflow.y:355
		{
			yyVAL.decllist = nil
		}
	case 48:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:357
		{
			yyVAL.decllist = append(yyDollar[1].decllist, yyDollar[2].decl)
		}
	case 49:
		yyDollar = yyS[yypt-2 : yypt+1]
//line reflow.y:361
		{
			yyVAL.decllist = []*Decl{yyDollar[1].decl}
		}
	case 50:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:363
		{
			yyVAL.decllist = append(yyDollar[1].decllist, yyDollar[2].decl)
		}
	case 51:
		yyDollar = yyS[yypt-0 : yypt+1]
//line reflow.y:366
		{
			yyVAL.decllist = nil
		}
	case 52:
		yyDollar = yyS[yypt-1 : yypt+1]
//line reflow.y:368
		{
			yyVAL.decllist = []*Decl{yyDollar[1].decl}
		}
	case 53:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:370
		{
			yyVAL.decllist = append(yyDollar[1].decllist, yyDollar[3].decl)
		}
	case 55:
		yyDollar = yyS[yypt-1 : yypt+1]
//line reflow.y:374
		{
			yyVAL.decl = &Decl{
				Position: yyDollar[1].expr.Position,
				Comment:  yyDollar[1].expr.Comment,
				Pat:      &Pat{Position: yyDollar[1].expr.Position, Kind: PatIdent, Ident: yyDollar[1].expr.Ident},
				Kind:     DeclAssign,
				Expr:     &Expr{Kind: ExprIdent, Ident: yyDollar[1].expr.Ident},
			}
		}
	case 56:
		yyDollar = yyS[yypt-0 : yypt+1]
//line reflow.y:385
		{
			yyVAL.decllist = nil
		}
	case 57:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:387
		{
			yyVAL.decllist = append(yyDollar[1].decllist, yyDollar[2].decllist...)
		}
	case 60:
		yyDollar = yyS[yypt-7 : yypt+1]
//line reflow.y:392
		{
			yyDollar[7].decl.Expr = &Expr{Position: yyDollar[7].decl.Expr.Position, Kind: ExprRequires, Left: yyDollar[7].decl.Expr, Decls: yyDollar[4].decllist}
			yyDollar[7].decl.Comment = yyDollar[1].pos.comment
			yyVAL.decl = yyDollar[7].decl
		}
	case 61:
		yyDollar = yyS[yypt-2 : yypt+1]
//line reflow.y:398
		{
			yyVAL.decl = yyDollar[2].decl
			yyVAL.decl.Comment = yyDollar[1].pos.comment
		}
	case 62:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:403
		{
			yyVAL.decl = &Decl{Position: yyDollar[1].expr.Position, Comment: yyDollar[1].expr.Comment, Pat: &Pat{Position: yyDollar[1].expr.Position, Kind: PatIdent, Ident: yyDollar[1].expr.Ident}, Kind: DeclAssign, Expr: yyDollar[3].expr}
		}
	case 63:
		yyDollar = yyS[yypt-7 : yypt+1]
//line reflow.y:405
		{
			yyVAL.decl = &Decl{Position: yyDollar[1].pos.Position, Comment: yyDollar[1].pos.comment, Pat: &Pat{Position: yyDollar[1].pos.Position, Kind: PatIdent, Ident: yyDollar[2].expr.Ident}, Kind: DeclAssign, Expr: &Expr{
				Kind: ExprFunc,
				Args: yyDollar[4].typfields,
				Left: yyDollar[7].expr}}
		}
	case 64:
		yyDollar = yyS[yypt-8 : yypt+1]
//line reflow.y:410
		{
			yyVAL.decl = &Decl{Position: yyDollar[1].pos.Position, Comment: yyDollar[1].pos.comment, Pat: &Pat{Position: yyDollar[1].pos.Position, Kind: PatIdent, Ident: yyDollar[2].expr.Ident}, Kind: DeclAssign, Expr: &Expr{
				Position: yyDollar[1].pos.Position,
				Kind:     ExprAscribe,
				Type:     types.Func(yyDollar[6].typ, yyDollar[4].typfields...),
				Left:     &Expr{Kind: ExprFunc, Args: yyDollar[4].typfields, Left: yyDollar[8].expr}}}
		}
	case 65:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:418
		{
			yyVAL.decl = &Decl{Position: yyDollar[1].pos.Position, Comment: yyDollar[1].pos.comment, Kind: DeclType, Ident: yyDollar[2].expr.Ident, Type: yyDollar[3].typ}
		}
	case 66:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:422
		{
			yyVAL.decl = &Decl{Position: yyDollar[3].expr.Position, Pat: yyDollar[1].pat, Kind: DeclAssign, Expr: yyDollar[3].expr}
		}
	case 67:
		yyDollar = yyS[yypt-4 : yypt+1]
//line reflow.y:424
		{
			yyVAL.decl = &Decl{
				Position: yyDollar[4].expr.Position,
				Pat:      yyDollar[1].pat,
				Kind:     DeclAssign,
				Expr: &Expr{
					Position: yyDollar[4].expr.Position,
					Kind:     ExprAscribe,
					Type:     yyDollar[2].typ,
					Left:     yyDollar[4].expr,
				},
			}
		}
	case 68:
		yyDollar = yyS[yypt-2 : yypt+1]
//line reflow.y:440
		{
			yyVAL.decllist = nil
			for i := range yyDollar[1].posidents.idents {
				yyVAL.decllist = append(yyVAL.decllist, &Decl{
					Position: yyDollar[1].posidents.pos,
					Comment:  yyDollar[1].posidents.comments[i],
					Ident:    yyDollar[1].posidents.idents[i],
					Kind:     DeclDeclare,
					Type:     yyDollar[2].typ,
				})
			}
		}
	case 69:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:453
		{
			if len(yyDollar[1].posidents.idents) != 1 {
				yyVAL.decllist = []*Decl{{Kind: DeclError}}
			} else {
				yyVAL.decllist = []*Decl{{Position: yyDollar[1].posidents.pos, Comment: yyDollar[1].posidents.comments[0], Pat: &Pat{Position: yyDollar[1].posidents.pos, Kind: PatIdent, Ident: yyDollar[1].posidents.idents[0]}, Kind: DeclAssign, Expr: yyDollar[3].expr}}
			}
		}
	case 70:
		yyDollar = yyS[yypt-4 : yypt+1]
//line reflow.y:461
		{
			if len(yyDollar[1].posidents.idents) != 1 {
				yyVAL.decllist = []*Decl{{Kind: DeclError}}
			} else {
				yyVAL.decllist = []*Decl{{
					Position: yyDollar[1].posidents.pos,
					Comment:  yyDollar[1].posidents.comments[0],
					Pat:      &Pat{Position: yyDollar[1].posidents.pos, Kind: PatIdent, Ident: yyDollar[1].posidents.idents[0]},
					Kind:     DeclAssign,
					Expr:     &Expr{Kind: ExprAscribe, Position: yyDollar[1].posidents.pos, Type: yyDollar[2].typ, Left: yyDollar[4].expr},
				}}
			}
		}
	case 71:
		yyDollar = yyS[yypt-1 : yypt+1]
//line reflow.y:477
		{
			yyVAL.posidents = posIdents{yyDollar[1].expr.Position, []string{yyDollar[1].expr.Ident}, []string{yyDollar[1].expr.Comment}}
		}
	case 72:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:479
		{
			yyVAL.posidents = posIdents{yyDollar[1].posidents.pos, append(yyDollar[1].posidents.idents, yyDollar[3].expr.Ident), append(yyDollar[1].posidents.comments, yyDollar[3].expr.Comment)}
		}
	case 74:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:485
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].expr.Position, Kind: ExprBinop, Op: "||", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 75:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:487
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].expr.Position, Kind: ExprBinop, Op: "&&", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 76:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:489
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].expr.Position, Kind: ExprBinop, Op: "<", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 77:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:491
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].expr.Position, Kind: ExprBinop, Op: ">", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 78:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:493
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].expr.Position, Kind: ExprBinop, Op: "<=", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 79:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:495
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].expr.Position, Kind: ExprBinop, Op: ">=", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 80:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:497
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].expr.Position, Kind: ExprBinop, Op: "!=", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 81:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:499
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].expr.Position, Kind: ExprBinop, Op: "==", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 82:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:501
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].expr.Position, Kind: ExprBinop, Op: "+", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 83:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:503
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].expr.Position, Kind: ExprBinop, Op: "-", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 84:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:505
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].expr.Position, Kind: ExprBinop, Op: "*", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 85:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:507
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].expr.Position, Kind: ExprBinop, Op: "/", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 86:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:509
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].expr.Position, Kind: ExprBinop, Op: "%", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 87:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:511
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].expr.Position, Kind: ExprBinop, Op: "&", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 88:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:513
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].expr.Position, Kind: ExprBinop, Op: "<<", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 89:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:515
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].expr.Position, Kind: ExprBinop, Op: ">>", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 90:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:517
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].expr.Position, Kind: ExprBinop, Op: "~>", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 91:
		yyDollar = yyS[yypt-4 : yypt+1]
//line reflow.y:519
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Comment: yyDollar[1].pos.comment, Kind: ExprCond, Cond: yyDollar[2].expr, Left: yyDollar[3].expr, Right: yyDollar[4].expr}
		}
	case 93:
		yyDollar = yyS[yypt-4 : yypt+1]
//line reflow.y:522
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].expr.Position, Kind: ExprIndex, Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 94:
		yyDollar = yyS[yypt-5 : yypt+1]
//line reflow.y:524
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].expr.Position, Kind: ExprApply, Left: yyDollar[1].expr, Fields: yyDollar[3].exprfields}
		}
	case 95:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:526
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].expr.Position, Kind: ExprDeref, Left: yyDollar[1].expr, Ident: yyDollar[3].expr.Ident}
		}
	case 96:
		yyDollar = yyS[yypt-2 : yypt+1]
//line reflow.y:528
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Kind: ExprUnop, Op: "!", Left: yyDollar[2].expr}
		}
	case 97:
		yyDollar = yyS[yypt-2 : yypt+1]
//line reflow.y:530
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Kind: ExprUnop, Op: "-", Left: yyDollar[2].expr}
		}
	case 98:
		yyDollar = yyS[yypt-2 : yypt+1]
//line reflow.y:534
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Kind: ExprBlock, Left: yyDollar[2].expr}
		}
	case 99:
		yyDollar = yyS[yypt-5 : yypt+1]
//line reflow.y:536
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Kind: ExprCond, Cond: yyDollar[3].expr, Left: yyDollar[4].expr, Right: yyDollar[5].expr}
		}
	case 102:
		yyDollar = yyS[yypt-1 : yypt+1]
//line reflow.y:543
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Kind: ExprIdent, Ident: "file"}
		}
	case 103:
		yyDollar = yyS[yypt-1 : yypt+1]
//line reflow.y:545
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Comment: yyDollar[1].pos.comment, Kind: ExprIdent, Ident: "dir"}
		}
	case 104:
		yyDollar = yyS[yypt-6 : yypt+1]
//line reflow.y:547
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Comment: yyDollar[1].pos.comment, Kind: ExprFunc, Args: yyDollar[3].typfields, Left: yyDollar[6].expr}
		}
	case 105:
		yyDollar = yyS[yypt-7 : yypt+1]
//line reflow.y:549
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Comment: yyDollar[1].pos.comment, Kind: ExprAscribe, Type: yyDollar[5].typ, Left: &Expr{
				Position: yyDollar[7].expr.Position, Kind: ExprFunc, Args: yyDollar[3].typfields, Left: yyDollar[7].expr}}
		}
	case 106:
		yyDollar = yyS[yypt-6 : yypt+1]
//line reflow.y:552
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Comment: yyDollar[1].pos.comment, Kind: ExprExec, Decls: yyDollar[3].decllist, Type: yyDollar[5].typ, Template: yyDollar[6].template}
		}
	case 107:
		yyDollar = yyS[yypt-4 : yypt+1]
//line reflow.y:554
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Comment: yyDollar[1].pos.comment, Kind: ExprMake, Left: yyDollar[3].expr}
		}
	case 108:
		yyDollar = yyS[yypt-7 : yypt+1]
//line reflow.y:556
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Comment: yyDollar[1].pos.comment, Kind: ExprMake, Left: yyDollar[3].expr, Decls: yyDollar[5].decllist}
		}
	case 109:
		yyDollar = yyS[yypt-6 : yypt+1]
//line reflow.y:558
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Comment: yyDollar[1].pos.comment, Kind: ExprTuple, Fields: append([]*FieldExpr{{Expr: yyDollar[2].expr}}, yyDollar[4].exprfields...)}
		}
	case 110:
		yyDollar = yyS[yypt-4 : yypt+1]
//line reflow.y:560
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Comment: yyDollar[1].pos.comment, Kind: ExprStruct, Fields: yyDollar[2].exprfields}
		}
	case 111:
		yyDollar = yyS[yypt-4 : yypt+1]
//line reflow.y:562
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Comment: yyDollar[1].pos.comment, Kind: ExprList, List: yyDollar[2].exprlist}
		}
	case 112:
		yyDollar = yyS[yypt-6 : yypt+1]
//line reflow.y:564
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Comment: yyDollar[1].pos.comment, Kind: ExprList, List: yyDollar[2].exprlist}
			for _, list := range yyDollar[4].exprlist {
				yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Kind: ExprBinop, Op: "+", Left: yyVAL.expr, Right: list}
			}
		}
	case 113:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:571
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Comment: yyDollar[1].pos.comment, Kind: ExprMap}
		}
	case 114:
		yyDollar = yyS[yypt-4 : yypt+1]
//line reflow.y:573
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Comment: yyDollar[1].pos.comment, Kind: ExprMap, Map: yyDollar[2].exprmap}
		}
	case 115:
		yyDollar = yyS[yypt-6 : yypt+1]
//line reflow.y:575
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Comment: yyDollar[1].pos.comment, Kind: ExprMap, Map: yyDollar[2].exprmap}
			for _, list := range yyDollar[4].exprlist {
				yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Kind: ExprBinop, Op: "+", Left: list, Right: yyVAL.expr}
			}
		}
	case 116:
		yyDollar = yyS[yypt-5 : yypt+1]
//line reflow.y:582
		{
			yyVAL.expr = &Expr{
				Position:     yyDollar[1].pos.Position,
				Comment:      yyDollar[1].pos.comment,
				Kind:         ExprCompr,
				ComprExpr:    yyDollar[2].expr,
				ComprClauses: yyDollar[4].comprclauses,
			}
		}
	case 117:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:592
		{
			yyVAL.expr = yyDollar[2].expr
		}
	case 119:
		yyDollar = yyS[yypt-4 : yypt+1]
//line reflow.y:595
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Comment: yyDollar[1].pos.comment, Kind: ExprBuiltin, Op: "len", Left: yyDollar[3].expr}
		}
	case 120:
		yyDollar = yyS[yypt-4 : yypt+1]
//line reflow.y:597
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].expr.Position, Comment: yyDollar[1].expr.Comment, Kind: ExprBuiltin, Op: "int", Left: yyDollar[3].expr}
		}
	case 121:
		yyDollar = yyS[yypt-4 : yypt+1]
//line reflow.y:599
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].expr.Position, Comment: yyDollar[1].expr.Comment, Kind: ExprBuiltin, Op: "float", Left: yyDollar[3].expr}
		}
	case 122:
		yyDollar = yyS[yypt-6 : yypt+1]
//line reflow.y:601
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Comment: yyDollar[1].pos.comment, Kind: ExprBuiltin, Op: "zip", Left: yyDollar[3].expr, Right: yyDollar[5].expr}
		}
	case 123:
		yyDollar = yyS[yypt-4 : yypt+1]
//line reflow.y:603
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Comment: yyDollar[1].pos.comment, Kind: ExprBuiltin, Op: "unzip", Left: yyDollar[3].expr}
		}
	case 124:
		yyDollar = yyS[yypt-4 : yypt+1]
//line reflow.y:605
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Comment: yyDollar[1].pos.comment, Kind: ExprBuiltin, Op: "flatten", Left: yyDollar[3].expr}
		}
	case 125:
		yyDollar = yyS[yypt-4 : yypt+1]
//line reflow.y:607
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Comment: yyDollar[1].pos.comment, Kind: ExprBuiltin, Op: "map", Left: yyDollar[3].expr}
		}
	case 126:
		yyDollar = yyS[yypt-6 : yypt+1]
//line reflow.y:609
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Comment: yyDollar[1].pos.comment, Kind: ExprBuiltin, Op: "range", Left: yyDollar[3].expr, Right: yyDollar[5].expr}
		}
	case 127:
		yyDollar = yyS[yypt-4 : yypt+1]
//line reflow.y:611
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Comment: yyDollar[1].pos.comment, Kind: ExprBuiltin, Op: "list", Left: yyDollar[3].expr}
		}
	case 128:
		yyDollar = yyS[yypt-4 : yypt+1]
//line reflow.y:613
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Comment: yyDollar[1].pos.comment, Kind: ExprBuiltin, Op: "delay", Left: yyDollar[3].expr}
		}
	case 129:
		yyDollar = yyS[yypt-4 : yypt+1]
//line reflow.y:615
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Comment: yyDollar[1].pos.comment, Kind: ExprBuiltin, Op: "panic", Left: yyDollar[3].expr}
		}
	case 130:
		yyDollar = yyS[yypt-4 : yypt+1]
//line reflow.y:617
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Comment: yyDollar[1].pos.comment, Kind: ExprBuiltin, Op: "trace", Left: yyDollar[3].expr}
		}
	case 131:
		yyDollar = yyS[yypt-5 : yypt+1]
//line reflow.y:621
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Comment: yyDollar[1].pos.comment, Kind: ExprBlock, Decls: yyDollar[2].decllist, Left: yyDollar[3].expr}
		}
	case 132:
		yyDollar = yyS[yypt-5 : yypt+1]
//line reflow.y:625
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Comment: yyDollar[1].pos.comment, Kind: ExprBlock, Decls: yyDollar[2].decllist, Left: yyDollar[3].expr}
		}
	case 133:
		yyDollar = yyS[yypt-5 : yypt+1]
//line reflow.y:629
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Comment: yyDollar[1].pos.comment, Kind: ExprSwitch, Left: yyDollar[2].expr, CaseClauses: yyDollar[4].caseclauses}
		}
	case 134:
		yyDollar = yyS[yypt-0 : yypt+1]
//line reflow.y:632
		{
			yyVAL.caseclauses = nil
		}
	case 135:
		yyDollar = yyS[yypt-2 : yypt+1]
//line reflow.y:634
		{
			yyVAL.caseclauses = append(yyDollar[1].caseclauses, yyDollar[2].caseclause)
		}
	case 136:
		yyDollar = yyS[yypt-5 : yypt+1]
//line reflow.y:638
		{
			yyVAL.caseclause = &CaseClause{Position: yyDollar[1].pos.Position, Comment: yyDollar[1].pos.comment, Pat: yyDollar[2].pat, Expr: yyDollar[4].expr}
		}
	case 139:
		yyDollar = yyS[yypt-2 : yypt+1]
//line reflow.y:644
		{
			yyVAL.expr = &Expr{Kind: ExprBlock, Decls: yyDollar[1].decllist, Left: yyDollar[2].expr}
		}
	case 140:
		yyDollar = yyS[yypt-1 : yypt+1]
//line reflow.y:648
		{
			yyVAL.comprclauses = []*ComprClause{yyDollar[1].comprclause}
		}
	case 141:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:650
		{
			yyVAL.comprclauses = append(yyDollar[1].comprclauses, yyDollar[3].comprclause)
		}
	case 142:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:654
		{
			yyVAL.comprclause = &ComprClause{Kind: ComprEnum, Pat: yyDollar[1].pat, Expr: yyDollar[3].expr}
		}
	case 143:
		yyDollar = yyS[yypt-2 : yypt+1]
//line reflow.y:656
		{
			yyVAL.comprclause = &ComprClause{Kind: ComprFilter, Expr: yyDollar[2].expr}
		}
	case 146:
		yyDollar = yyS[yypt-1 : yypt+1]
//line reflow.y:663
		{
			yyVAL.exprfields = []*FieldExpr{yyDollar[1].exprfield}
		}
	case 147:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:665
		{
			yyVAL.exprfields = append(yyDollar[1].exprfields, yyDollar[3].exprfield)
		}
	case 148:
		yyDollar = yyS[yypt-1 : yypt+1]
//line reflow.y:669
		{
			yyVAL.exprfield = &FieldExpr{Name: yyDollar[1].expr.Ident, Expr: &Expr{Position: yyDollar[1].expr.Position, Kind: ExprIdent, Ident: yyDollar[1].expr.Ident}}
		}
	case 149:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:671
		{
			yyVAL.exprfield = &FieldExpr{Name: yyDollar[1].expr.Ident, Expr: yyDollar[3].expr}
		}
	case 150:
		yyDollar = yyS[yypt-0 : yypt+1]
//line reflow.y:674
		{
			yyVAL.exprlist = nil
		}
	case 151:
		yyDollar = yyS[yypt-1 : yypt+1]
//line reflow.y:676
		{
			yyVAL.exprlist = []*Expr{yyDollar[1].expr}
		}
	case 152:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:678
		{
			yyVAL.exprlist = append(yyDollar[1].exprlist, yyDollar[3].expr)
		}
	case 153:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:682
		{
			yyVAL.exprlist = []*Expr{yyDollar[2].expr}
		}
	case 154:
		yyDollar = yyS[yypt-4 : yypt+1]
//line reflow.y:684
		{
			yyVAL.exprlist = append(yyDollar[1].exprlist, yyDollar[3].expr)
		}
	case 155:
		yyDollar = yyS[yypt-1 : yypt+1]
//line reflow.y:688
		{
			yyVAL.exprfields = []*FieldExpr{{Expr: yyDollar[1].expr}}
		}
	case 156:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:690
		{
			yyVAL.exprfields = append(yyDollar[1].exprfields, &FieldExpr{Expr: yyDollar[3].expr})
		}
	case 157:
		yyDollar = yyS[yypt-1 : yypt+1]
//line reflow.y:694
		{
			yyVAL.exprfields = []*FieldExpr{{Expr: yyDollar[1].expr}}
		}
	case 158:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:696
		{
			yyVAL.exprfields = append(yyDollar[1].exprfields, &FieldExpr{Expr: yyDollar[3].expr})
		}
	case 159:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:700
		{
			yyVAL.exprmap = map[*Expr]*Expr{yyDollar[1].expr: yyDollar[3].expr}
		}
	case 160:
		yyDollar = yyS[yypt-5 : yypt+1]
//line reflow.y:702
		{
			yyVAL.exprmap = yyDollar[1].exprmap
			yyVAL.exprmap[yyDollar[3].expr] = yyDollar[5].expr
		}
	case 162:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:713
		{
			yyVAL.module = &ModuleImpl{Keyspace: yyDollar[1].expr, ParamDecls: yyDollar[2].decllist, Decls: yyDollar[3].decllist}
		}
	case 163:
		yyDollar = yyS[yypt-0 : yypt+1]
//line reflow.y:716
		{
			yyVAL.expr = nil
		}
	case 164:
		yyDollar = yyS[yypt-2 : yypt+1]
//line reflow.y:718
		{
			yyVAL.expr = yyDollar[2].expr
		}
	case 165:
		yyDollar = yyS[yypt-0 : yypt+1]
//line reflow.y:721
		{
			yyVAL.decllist = nil
		}
	case 166:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:723
		{
			yyVAL.decllist = append(yyDollar[1].decllist, yyDollar[2].decllist...)
		}
	case 167:
		yyDollar = yyS[yypt-0 : yypt+1]
//line reflow.y:726
		{
			yyVAL.decllist = nil
		}
	case 168:
		yyDollar = yyS[yypt-2 : yypt+1]
//line reflow.y:728
		{
			yyVAL.decllist = yyDollar[2].decllist
		}
	case 169:
		yyDollar = yyS[yypt-4 : yypt+1]
//line reflow.y:730
		{
			yyVAL.decllist = yyDollar[3].decllist
		}
	}
	goto yystack /* stack new state and value */
}
