// Code generated by goyacc reflow.y. DO NOT EDIT.

//line reflow.y:2
package syntax

import __yyfmt__ "fmt"

//line reflow.y:2

import (
	"fmt"

	"github.com/grailbio/reflow/internal/scanner"
	"github.com/grailbio/reflow/types"
)

type posIdents struct {
	pos      scanner.Position
	idents   []string
	comments []string
}

type typearg struct {
	t1, t2 *types.T
}

//line reflow.y:23
type yySymType struct {
	yys int
	pos struct {
		scanner.Position
		comment string
	}
	expr       *Expr
	exprlist   []*Expr
	exprfield  *FieldExpr
	exprfields []*FieldExpr
	exprmap    map[*Expr]*Expr

	comprclauses []*ComprClause
	comprclause  *ComprClause

	typ         *types.T
	typlist     []*types.T
	typfield    *types.Field
	typfields   []*types.Field
	decl        *Decl
	decllist    []*Decl
	pat         *Pat
	patlist     []*Pat
	caseclause  *CaseClause
	caseclauses []*CaseClause
	tok         int
	template    *Template

	structpat struct {
		field string
		pat   *Pat
	}

	structpats []struct {
		field string
		pat   *Pat
	}

	listpats struct {
		list []*Pat
		tail *Pat
	}

	typearg  typearg
	typeargs []typearg

	module *ModuleImpl

	str string

	idents    []string
	posidents posIdents
}

const tokIdent = 57346
const tokExpr = 57347
const tokInt = 57348
const tokString = 57349
const tokBool = 57350
const tokFloat = 57351
const tokTemplate = 57352
const tokFile = 57353
const tokDir = 57354
const tokStruct = 57355
const tokModule = 57356
const tokExec = 57357
const tokAs = 57358
const tokAt = 57359
const tokVal = 57360
const tokFunc = 57361
const tokAssign = 57362
const tokArrow = 57363
const tokLeftArrow = 57364
const tokIf = 57365
const tokElse = 57366
const tokSwitch = 57367
const tokCase = 57368
const tokMake = 57369
const tokLen = 57370
const tokPanic = 57371
const tokDelay = 57372
const tokTrace = 57373
const tokMap = 57374
const tokList = 57375
const tokZip = 57376
const tokUnzip = 57377
const tokFlatten = 57378
const tokStartModule = 57379
const tokStartDecls = 57380
const tokStartExpr = 57381
const tokStartType = 57382
const tokStartPat = 57383
const tokKeyspace = 57384
const tokParam = 57385
const tokEllipsis = 57386
const tokReserved = 57387
const tokRequires = 57388
const tokRange = 57389
const tokType = 57390
const tokOrOr = 57391
const tokAndAnd = 57392
const tokLE = 57393
const tokGE = 57394
const tokNE = 57395
const tokEqEq = 57396
const tokLSH = 57397
const tokRSH = 57398
const tokSquiggleArrow = 57399
const tokEOF = 57400
const tokError = 57401
const first = 57402
const unary = 57403
const apply = 57404
const deref = 57405

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"tokIdent",
	"tokExpr",
	"tokInt",
	"tokString",
	"tokBool",
	"tokFloat",
	"tokTemplate",
	"tokFile",
	"tokDir",
	"tokStruct",
	"tokModule",
	"tokExec",
	"tokAs",
	"tokAt",
	"tokVal",
	"tokFunc",
	"tokAssign",
	"tokArrow",
	"tokLeftArrow",
	"tokIf",
	"tokElse",
	"tokSwitch",
	"tokCase",
	"tokMake",
	"tokLen",
	"tokPanic",
	"tokDelay",
	"tokTrace",
	"tokMap",
	"tokList",
	"tokZip",
	"tokUnzip",
	"tokFlatten",
	"tokStartModule",
	"tokStartDecls",
	"tokStartExpr",
	"tokStartType",
	"tokStartPat",
	"tokKeyspace",
	"tokParam",
	"tokEllipsis",
	"tokReserved",
	"tokRequires",
	"tokRange",
	"tokType",
	"'{'",
	"'('",
	"'['",
	"tokOrOr",
	"tokAndAnd",
	"tokLE",
	"tokGE",
	"tokNE",
	"tokEqEq",
	"tokLSH",
	"tokRSH",
	"tokSquiggleArrow",
	"'<'",
	"'>'",
	"'+'",
	"'-'",
	"'|'",
	"'^'",
	"'*'",
	"'/'",
	"'%'",
	"'&'",
	"'_'",
	"'!'",
	"tokEOF",
	"tokError",
	"first",
	"unary",
	"'.'",
	"']'",
	"')'",
	"apply",
	"deref",
	"':'",
	"'}'",
	"','",
	"';'",
	"'='",
}
var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line yacctab:1
var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 62,
	85, 166,
	-2, 46,
}

const yyPrivate = 57344

const yyLast = 1414

var yyAct = [...]int{

	11, 102, 181, 247, 261, 66, 134, 358, 180, 175,
	272, 177, 41, 65, 94, 234, 95, 96, 133, 142,
	186, 265, 179, 103, 380, 100, 127, 109, 104, 131,
	341, 10, 306, 262, 359, 367, 273, 344, 327, 292,
	218, 122, 251, 55, 328, 253, 178, 260, 252, 233,
	254, 230, 231, 251, 352, 54, 125, 42, 44, 45,
	43, 228, 46, 47, 322, 51, 226, 229, 217, 218,
	53, 227, 377, 192, 147, 154, 155, 156, 157, 158,
	159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
	169, 170, 171, 173, 144, 138, 140, 126, 335, 319,
	50, 52, 49, 189, 323, 188, 150, 218, 246, 223,
	198, 201, 202, 203, 204, 205, 206, 207, 208, 209,
	210, 211, 212, 195, 187, 373, 320, 194, 257, 197,
	215, 92, 91, 151, 216, 220, 193, 370, 232, 88,
	89, 224, 375, 354, 82, 83, 237, 65, 84, 85,
	86, 87, 241, 346, 308, 333, 294, 240, 93, 54,
	243, 42, 44, 45, 43, 225, 46, 47, 54, 51,
	42, 44, 45, 43, 53, 46, 47, 221, 51, 250,
	92, 91, 266, 53, 222, 256, 360, 356, 266, 336,
	196, 124, 136, 245, 263, 193, 267, 123, 61, 270,
	152, 275, 242, 237, 50, 52, 49, 93, 249, 92,
	91, 258, 311, 50, 52, 49, 268, 88, 89, 269,
	238, 340, 264, 289, 135, 56, 84, 85, 86, 87,
	121, 120, 119, 118, 117, 116, 93, 115, 176, 303,
	305, 302, 293, 301, 274, 290, 97, 309, 219, 235,
	312, 298, 65, 114, 307, 113, 112, 314, 310, 316,
	315, 304, 111, 110, 295, 99, 296, 324, 98, 299,
	60, 58, 59, 97, 70, 330, 318, 317, 130, 56,
	331, 148, 146, 9, 332, 182, 321, 68, 69, 71,
	325, 70, 57, 248, 329, 350, 105, 151, 68, 69,
	71, 337, 56, 342, 68, 69, 71, 345, 343, 68,
	69, 71, 347, 351, 349, 183, 339, 348, 72, 297,
	355, 63, 129, 357, 60, 58, 59, 361, 143, 72,
	363, 291, 259, 214, 338, 72, 174, 153, 353, 362,
	72, 70, 368, 64, 152, 1, 57, 60, 58, 59,
	139, 374, 369, 371, 68, 69, 71, 372, 137, 141,
	145, 315, 62, 7, 255, 376, 172, 101, 236, 57,
	128, 379, 366, 132, 48, 378, 381, 271, 383, 385,
	104, 386, 108, 106, 334, 288, 388, 387, 188, 18,
	17, 29, 384, 382, 30, 14, 19, 20, 27, 8,
	22, 12, 67, 149, 21, 300, 0, 0, 13, 0,
	40, 0, 23, 28, 38, 37, 39, 34, 36, 31,
	32, 33, 0, 2, 3, 4, 5, 6, 0, 0,
	0, 0, 35, 0, 25, 24, 26, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 16,
	0, 54, 0, 42, 44, 45, 43, 15, 46, 47,
	0, 51, 0, 0, 0, 0, 53, 107, 92, 91,
	74, 75, 78, 79, 80, 81, 88, 89, 90, 76,
	77, 82, 83, 0, 0, 84, 85, 86, 87, 0,
	0, 0, 0, 0, 0, 93, 50, 52, 49, 0,
	0, 0, 0, 359, 92, 91, 74, 75, 78, 79,
	80, 81, 88, 89, 90, 76, 77, 82, 83, 0,
	0, 84, 85, 86, 87, 0, 0, 0, 0, 0,
	0, 93, 0, 239, 0, 0, 0, 0, 0, 262,
	92, 91, 74, 75, 78, 79, 80, 81, 88, 89,
	90, 76, 77, 82, 83, 0, 0, 84, 85, 86,
	87, 0, 0, 0, 0, 0, 0, 93, 0, 185,
	0, 0, 0, 0, 184, 92, 91, 74, 75, 78,
	79, 80, 81, 88, 89, 90, 76, 77, 82, 83,
	0, 0, 84, 85, 86, 87, 0, 0, 0, 0,
	0, 0, 93, 0, 0, 0, 0, 0, 0, 283,
	92, 91, 74, 75, 78, 79, 80, 81, 88, 89,
	90, 76, 77, 82, 83, 0, 0, 84, 85, 86,
	87, 0, 0, 0, 0, 0, 0, 93, 0, 0,
	0, 0, 0, 0, 279, 92, 91, 74, 75, 78,
	79, 80, 81, 88, 89, 90, 76, 77, 82, 83,
	199, 0, 84, 85, 86, 87, 0, 0, 0, 0,
	0, 0, 93, 0, 0, 0, 0, 200, 92, 91,
	74, 75, 78, 79, 80, 81, 88, 89, 90, 76,
	77, 82, 83, 0, 0, 84, 85, 86, 87, 0,
	0, 190, 17, 29, 0, 93, 30, 0, 19, 20,
	326, 0, 22, 0, 68, 69, 191, 0, 0, 0,
	13, 0, 40, 0, 23, 28, 38, 37, 39, 34,
	36, 31, 32, 33, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 35, 72, 25, 24, 26, 54,
	0, 42, 44, 45, 43, 0, 46, 47, 0, 51,
	0, 16, 0, 0, 53, 0, 313, 0, 0, 15,
	92, 91, 74, 75, 78, 79, 80, 81, 88, 89,
	90, 76, 77, 82, 83, 0, 0, 84, 85, 86,
	87, 0, 0, 0, 50, 52, 49, 93, 0, 365,
	92, 91, 74, 75, 78, 79, 80, 81, 88, 89,
	90, 76, 77, 82, 83, 0, 0, 84, 85, 86,
	87, 0, 0, 0, 0, 0, 0, 93, 0, 364,
	92, 91, 74, 75, 78, 79, 80, 81, 88, 89,
	90, 76, 77, 82, 83, 0, 0, 84, 85, 86,
	87, 0, 0, 0, 0, 0, 0, 93, 0, 287,
	92, 91, 74, 75, 78, 79, 80, 81, 88, 89,
	90, 76, 77, 82, 83, 0, 0, 84, 85, 86,
	87, 0, 0, 0, 0, 0, 0, 93, 0, 286,
	92, 91, 74, 75, 78, 79, 80, 81, 88, 89,
	90, 76, 77, 82, 83, 0, 0, 84, 85, 86,
	87, 0, 0, 0, 0, 0, 0, 93, 0, 285,
	92, 91, 74, 75, 78, 79, 80, 81, 88, 89,
	90, 76, 77, 82, 83, 0, 0, 84, 85, 86,
	87, 0, 0, 0, 0, 0, 0, 93, 0, 284,
	92, 91, 74, 75, 78, 79, 80, 81, 88, 89,
	90, 76, 77, 82, 83, 0, 0, 84, 85, 86,
	87, 0, 0, 0, 0, 0, 0, 93, 0, 282,
	92, 91, 74, 75, 78, 79, 80, 81, 88, 89,
	90, 76, 77, 82, 83, 0, 0, 84, 85, 86,
	87, 0, 0, 0, 0, 0, 0, 93, 0, 281,
	92, 91, 74, 75, 78, 79, 80, 81, 88, 89,
	90, 76, 77, 82, 83, 0, 0, 84, 85, 86,
	87, 0, 0, 0, 0, 0, 0, 93, 0, 280,
	92, 91, 74, 75, 78, 79, 80, 81, 88, 89,
	90, 76, 77, 82, 83, 0, 0, 84, 85, 86,
	87, 0, 0, 0, 0, 0, 0, 93, 0, 278,
	92, 91, 74, 75, 78, 79, 80, 81, 88, 89,
	90, 76, 77, 82, 83, 0, 0, 84, 85, 86,
	87, 0, 0, 0, 0, 0, 0, 93, 0, 277,
	92, 91, 74, 75, 78, 79, 80, 81, 88, 89,
	90, 76, 77, 82, 83, 0, 0, 84, 85, 86,
	87, 0, 0, 0, 0, 0, 0, 93, 0, 276,
	92, 91, 74, 75, 78, 79, 80, 81, 88, 89,
	90, 76, 77, 82, 83, 0, 0, 84, 85, 86,
	87, 0, 0, 0, 18, 17, 29, 93, 244, 30,
	0, 19, 20, 0, 0, 22, 0, 0, 0, 21,
	0, 0, 0, 13, 0, 40, 0, 23, 28, 38,
	37, 39, 34, 36, 31, 32, 33, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 35, 0, 25,
	24, 26, 54, 0, 42, 44, 45, 43, 0, 46,
	47, 0, 51, 0, 16, 0, 0, 53, 0, 0,
	0, 0, 15, 176, 92, 91, 74, 75, 78, 79,
	80, 81, 88, 89, 90, 76, 77, 82, 83, 0,
	0, 84, 85, 86, 87, 0, 0, 50, 52, 49,
	0, 93, 213, 92, 91, 74, 75, 78, 79, 80,
	81, 88, 89, 90, 76, 77, 82, 83, 0, 0,
	84, 85, 86, 87, 0, 0, 0, 0, 0, 0,
	93, 92, 91, 74, 75, 78, 79, 80, 81, 88,
	89, 90, 76, 77, 82, 83, 0, 0, 84, 85,
	86, 87, 0, 0, 73, 0, 0, 0, 93, 92,
	91, 74, 75, 78, 79, 80, 81, 88, 89, 90,
	76, 77, 82, 83, 0, 0, 84, 85, 86, 87,
	0, 0, 0, 0, 0, 0, 93, 92, 91, 74,
	75, 78, 79, 80, 81, 88, 89, 0, 76, 77,
	82, 83, 0, 0, 84, 85, 86, 87, 0, 0,
	0, 0, 92, 91, 93, 75, 78, 79, 80, 81,
	88, 89, 0, 76, 77, 82, 83, 0, 0, 84,
	85, 86, 87, 0, 0, 0, 92, 91, 0, 93,
	78, 79, 80, 81, 88, 89, 0, 76, 77, 82,
	83, 0, 0, 84, 85, 86, 87, 0, 0, 0,
	0, 0, 0, 93,
}
var yyPact = [...]int{

	386, -1000, 241, -1000, 1150, 1198, 298, 125, -1000, 316,
	270, 1231, -1000, 1150, -1000, 1150, 1150, -1000, -1000, -1000,
	-1000, 223, 218, 215, 1150, 292, 385, -1000, 213, 212,
	206, 205, 203, 187, 185, 184, 183, 182, 181, 180,
	1150, 124, -1000, -1000, -1000, -1000, -1000, -1000, 114, 1198,
	318, 229, 1198, 174, -1000, 119, -1000, -1000, 298, 298,
	324, -1000, 239, -1000, -1000, -11, -1000, -1000, 235, 298,
	277, 340, 333, -1000, 1150, 1150, 1150, 1150, 1150, 1150,
	1150, 1150, 1150, 1150, 1150, 1150, 1150, 1150, 1150, 1150,
	1150, 1150, 1150, 332, 1174, 130, 130, 318, 281, 310,
	490, 40, 697, -1000, -12, 113, 39, 112, 26, 595,
	1150, 1150, 1150, 1150, 1150, 1150, 1150, 1150, 1150, 1150,
	1150, 1150, 1203, -1000, 329, 52, -15, -1000, 164, -1000,
	318, 105, 25, -1000, 1198, 1198, -1000, -13, -1000, -17,
	-1000, -32, -1000, 56, 287, -36, 199, -1000, 170, -1000,
	447, 1150, 152, 1198, 1312, 1336, 81, 81, 81, 81,
	81, 81, 159, 159, 130, 130, 130, 130, 130, 130,
	1287, 1080, 24, 1259, -1000, 269, -1000, 100, 23, -31,
	-1000, -1000, 277, -34, 1150, -1000, 45, 328, -38, 454,
	277, 196, -1000, 1150, 144, 1150, -1000, 138, 1150, 221,
	1150, 1050, 1020, 990, 560, 960, 930, 900, 525, 870,
	840, 810, 780, -1000, -1000, -1000, 1198, -1000, 318, 327,
	-1000, -44, -1000, 1198, -1000, 77, -1000, 298, -1000, 275,
	-1000, 324, 298, -1000, -1000, -1000, 155, -1000, 281, 1150,
	-54, 1259, 318, -1000, -1000, 75, 1150, -1000, 189, 697,
	745, 281, 1198, -1000, 281, 15, 1259, -1000, -1000, 54,
	-1000, 43, -1000, 1259, -1000, 20, 1150, 1259, -1000, 20,
	628, -40, -1000, 272, 1150, 1259, -1000, -1000, -1000, 1150,
	-1000, -1000, -1000, 1150, -1000, -1000, -1000, -1000, 72, 111,
	-1000, -1000, -1000, -1000, 1198, -1000, -1000, 298, -1000, -1000,
	142, -56, 1150, 304, -42, 1259, 1150, 74, -1000, 1259,
	-1000, 1150, 454, 1150, 274, -1000, 303, -30, 64, 1150,
	-1000, 109, 1150, -1000, 418, 108, 1150, -1000, 221, 1150,
	1259, 750, 720, -1000, -1000, 298, -1000, -1000, -1000, -50,
	-1000, 1150, 1259, -1000, -51, 1259, 51, 1174, 42, 1259,
	1150, -1000, 281, 63, -1000, 1259, -1000, 418, -1000, -1000,
	-1000, 1259, -1000, 1259, -1000, -1000, -10, -1000, 1259, 337,
	1150, -62, 269, -1000, 1259, -1000, -1000, 697, -1000, 1259,
	1150, -1000, -52, 1259, -1000, 697, 1259, -1000, 1259,
}
var yyPgo = [...]int{

	0, 31, 1, 22, 15, 405, 403, 5, 402, 2,
	8, 0, 401, 399, 398, 9, 3, 395, 393, 392,
	385, 384, 383, 21, 382, 377, 10, 374, 6, 18,
	373, 29, 46, 26, 11, 370, 368, 23, 367, 366,
	364, 363, 362, 360, 36, 19, 359, 358, 350, 345,
	7, 20, 4,
}
var yyR1 = [...]int{

	0, 49, 49, 49, 49, 49, 27, 27, 28, 28,
	28, 28, 28, 28, 28, 28, 28, 28, 28, 28,
	28, 35, 35, 33, 32, 32, 29, 29, 30, 30,
	31, 44, 44, 44, 44, 44, 48, 48, 48, 48,
	47, 47, 46, 46, 45, 45, 1, 1, 2, 2,
	3, 3, 3, 10, 10, 5, 5, 9, 9, 7,
	7, 7, 7, 7, 8, 6, 6, 4, 4, 4,
	36, 36, 11, 11, 11, 11, 11, 11, 11, 11,
	11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
	11, 11, 11, 11, 11, 11, 11, 16, 16, 12,
	12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
	12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
	12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
	14, 15, 17, 20, 20, 21, 18, 18, 19, 25,
	25, 26, 26, 52, 52, 38, 38, 37, 37, 22,
	22, 22, 23, 23, 40, 40, 39, 39, 24, 24,
	34, 41, 13, 13, 42, 42, 43, 43, 43, 51,
	51, 50, 50,
}
var yyR2 = [...]int{

	0, 3, 3, 3, 3, 3, 1, 3, 1, 1,
	1, 1, 1, 1, 1, 3, 5, 3, 4, 3,
	5, 1, 3, 2, 1, 3, 1, 2, 1, 3,
	1, 1, 1, 3, 3, 3, 1, 3, 3, 4,
	1, 3, 1, 3, 1, 3, 0, 3, 2, 3,
	0, 1, 3, 1, 1, 0, 3, 1, 1, 7,
	2, 3, 7, 8, 3, 3, 4, 2, 3, 4,
	1, 3, 1, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	4, 1, 4, 5, 3, 2, 2, 2, 5, 1,
	1, 1, 1, 6, 7, 6, 4, 7, 6, 4,
	4, 6, 3, 4, 6, 5, 3, 1, 4, 4,
	4, 6, 4, 4, 4, 6, 4, 4, 4, 4,
	5, 5, 5, 0, 2, 5, 1, 1, 2, 1,
	3, 3, 2, 0, 1, 1, 3, 1, 3, 0,
	1, 3, 3, 4, 1, 3, 1, 3, 3, 5,
	1, 3, 0, 2, 0, 3, 0, 2, 4, 0,
	1, 0, 1,
}
var yyChk = [...]int{

	-1000, -49, 37, 38, 39, 40, 41, -41, -13, 42,
	-1, -11, -12, 23, -17, 72, 64, 5, 4, 11,
	12, 19, 15, 27, 50, 49, 51, -14, 28, 6,
	9, 34, 35, 36, 32, 47, 33, 30, 29, 31,
	25, -28, 6, 9, 7, 8, 11, 12, -27, 51,
	49, 14, 50, 19, 4, -44, 4, 71, 50, 51,
	49, 73, -42, 5, 73, -9, -7, -8, 17, 18,
	4, 19, 48, 73, 52, 53, 61, 62, 54, 55,
	56, 57, 63, 64, 67, 68, 69, 70, 58, 59,
	60, 51, 50, 77, -11, -11, -11, 50, 50, 50,
	-11, -38, -2, -37, -9, 4, -22, 82, -24, -11,
	50, 50, 50, 50, 50, 50, 50, 50, 50, 50,
	50, 50, -11, 73, 77, -28, -32, -33, -35, 4,
	49, -31, -30, -29, -28, 50, 73, -47, -44, -48,
	-44, -46, -45, 4, -1, -43, 43, 85, 46, -6,
	-44, 20, 4, 4, -11, -11, -11, -11, -11, -11,
	-11, -11, -11, -11, -11, -11, -11, -11, -11, -11,
	-11, -11, -39, -11, 4, -15, 49, -34, -32, -3,
	-10, -9, 4, 5, 84, 79, -51, 84, -9, -11,
	4, 19, 85, 82, -51, 84, 78, -51, 84, 65,
	82, -11, -11, -11, -11, -11, -11, -11, -11, -11,
	-11, -11, -11, 49, 4, 78, 82, 83, 84, 84,
	-28, -32, 79, 84, -28, -31, 79, 84, 78, 84,
	83, 84, 82, 85, -4, 50, -36, 4, 50, 86,
	-28, -11, 50, -28, 78, -51, 84, -16, 24, -1,
	79, 84, 79, 79, 84, -40, -11, 83, -37, 4,
	85, -52, 85, -11, 78, -23, 44, -11, 78, -23,
	-11, -25, -26, -44, 23, -11, 79, 79, 79, 84,
	79, 79, 79, 84, 79, 79, 79, 79, -20, -28,
	-33, 4, 83, -29, 79, -44, -44, 44, -45, -44,
	-5, -28, 86, 84, -3, -11, 86, -34, 79, -11,
	-15, 23, -11, 21, -28, -10, -28, -3, -51, 84,
	83, -51, 44, 84, -11, -51, 82, 78, 84, 22,
	-11, -11, -11, 83, -21, 26, 78, -28, -44, -4,
	79, 86, -11, 4, 79, -11, 79, -11, -52, -11,
	21, 10, 84, -51, 79, -11, 78, -11, -50, 85,
	78, -11, -26, -11, 79, 79, -44, 85, -11, -50,
	86, -28, -15, 83, -11, 79, -50, 82, -7, -11,
	86, -16, -18, -11, -19, -2, -11, -52, -11,
}
var yyDef = [...]int{

	0, -2, 162, 46, 0, 0, 0, 0, 164, 0,
	0, 0, 72, 0, 91, 0, 0, 99, 100, 101,
	102, 0, 0, 0, 0, 0, 149, 117, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 8, 9, 10, 11, 12, 13, 14, 0,
	0, 0, 0, 0, 6, 0, 31, 32, 0, 0,
	0, 1, -2, 163, 2, 0, 57, 58, 0, 0,
	0, 0, 0, 3, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 95, 96, 0, 50, 0,
	0, 169, 0, 145, 0, 147, 169, 0, 169, 150,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 4, 0, 0, 0, 24, 0, 21,
	0, 0, 30, 28, 26, 0, 5, 0, 40, 0,
	36, 0, 42, 44, 161, 0, 0, 47, 0, 60,
	0, 0, 0, 0, 73, 74, 75, 76, 77, 78,
	79, 80, 81, 82, 83, 84, 85, 86, 87, 88,
	89, 0, 169, 156, 94, 0, 46, 0, 160, 0,
	51, 53, 54, 0, 0, 116, 0, 170, 0, 143,
	100, 0, 48, 0, 0, 170, 112, 0, 170, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 133, 7, 15, 0, 17, 0, 0,
	23, 0, 19, 0, 27, 0, 33, 0, 34, 0,
	35, 0, 0, 165, 167, 55, 0, 70, 50, 0,
	0, 61, 0, 64, 92, 0, 170, 90, 0, 0,
	0, 0, 0, 106, 50, 169, 154, 109, 146, 147,
	49, 0, 144, 148, 110, 169, 0, 151, 113, 169,
	0, 0, 139, 0, 0, 158, 118, 119, 120, 0,
	122, 123, 124, 0, 126, 127, 128, 129, 0, 0,
	25, 22, 18, 29, 0, 41, 37, 38, 43, 45,
	0, 67, 0, 0, 0, 65, 0, 0, 93, 157,
	97, 0, 143, 0, 0, 52, 0, 169, 0, 170,
	130, 0, 0, 170, 171, 0, 0, 115, 0, 0,
	142, 0, 0, 132, 134, 0, 16, 20, 39, 0,
	168, 0, 68, 71, 171, 66, 0, 0, 0, 103,
	0, 105, 170, 0, 108, 155, 111, 171, 152, 172,
	114, 159, 140, 141, 121, 125, 0, 56, 69, 0,
	0, 0, 0, 131, 104, 107, 153, 0, 59, 62,
	0, 98, 143, 136, 137, 0, 63, 135, 138,
}
var yyTok1 = [...]int{

	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 72, 3, 3, 3, 69, 70, 3,
	50, 79, 67, 63, 84, 64, 77, 68, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 82, 85,
	61, 86, 62, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 51, 3, 78, 66, 71, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 49, 65, 83,
}
var yyTok2 = [...]int{

	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 52, 53, 54,
	55, 56, 57, 58, 59, 60, 73, 74, 75, 76,
	80, 81,
}
var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:138
		{
			yylex.(*Parser).Module = yyDollar[2].module
			return 0
		}
	case 2:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:143
		{
			yylex.(*Parser).Decls = yyDollar[2].decllist
			return 0
		}
	case 3:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:148
		{
			yylex.(*Parser).Expr = yyDollar[2].expr
			return 0
		}
	case 4:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:153
		{
			yylex.(*Parser).Type = yyDollar[2].typ
			return 0
		}
	case 5:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:158
		{
			yylex.(*Parser).Pat = yyDollar[2].pat
			return 0
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
//line reflow.y:169
		{
			yyVAL.idents = []string{yyDollar[1].expr.Ident}
		}
	case 7:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:171
		{
			yyVAL.idents = append(yyDollar[1].idents, yyDollar[3].expr.Ident)
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
//line reflow.y:174
		{
			yyVAL.typ = types.Int
		}
	case 9:
		yyDollar = yyS[yypt-1 : yypt+1]
//line reflow.y:175
		{
			yyVAL.typ = types.Float
		}
	case 10:
		yyDollar = yyS[yypt-1 : yypt+1]
//line reflow.y:176
		{
			yyVAL.typ = types.String
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
//line reflow.y:177
		{
			yyVAL.typ = types.Bool
		}
	case 12:
		yyDollar = yyS[yypt-1 : yypt+1]
//line reflow.y:178
		{
			yyVAL.typ = types.File
		}
	case 13:
		yyDollar = yyS[yypt-1 : yypt+1]
//line reflow.y:179
		{
			yyVAL.typ = types.Dir
		}
	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
//line reflow.y:180
		{
			yyVAL.typ = types.Ref(yyDollar[1].idents...)
		}
	case 15:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:181
		{
			yyVAL.typ = types.List(yyDollar[2].typ)
		}
	case 16:
		yyDollar = yyS[yypt-5 : yypt+1]
//line reflow.y:183
		{
			yyVAL.typ = types.Map(yyDollar[2].typ, yyDollar[4].typ)
		}
	case 17:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:185
		{
			yyVAL.typ = types.Struct(yyDollar[2].typfields...)
		}
	case 18:
		yyDollar = yyS[yypt-4 : yypt+1]
//line reflow.y:187
		{
			yyVAL.typ = types.Module(yyDollar[3].typfields, nil)
		}
	case 19:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:189
		{
			switch len(yyDollar[2].typfields) {
			// "()" is unit
			case 0:
				yyVAL.typ = types.Unit
				// "(type)" and "(name type)" get collapsed with
			// (optional) label
			case 1:
				yyVAL.typ = types.Labeled(yyDollar[2].typfields[0].Name, yyDollar[2].typfields[0].T)
				// a regular tuple must have at least two members
			default:
				yyVAL.typ = types.Tuple(yyDollar[2].typfields...)
			}
		}
	case 20:
		yyDollar = yyS[yypt-5 : yypt+1]
//line reflow.y:201
		{
			yyVAL.typ = types.Func(yyDollar[5].typ, yyDollar[3].typfields...)
		}
	case 21:
		yyDollar = yyS[yypt-1 : yypt+1]
//line reflow.y:205
		{
			yyVAL.idents = []string{yyDollar[1].expr.Ident}
		}
	case 22:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:207
		{
			yyVAL.idents = append(yyDollar[1].idents, yyDollar[3].expr.Ident)
		}
	case 23:
		yyDollar = yyS[yypt-2 : yypt+1]
//line reflow.y:211
		{
			for _, name := range yyDollar[1].idents {
				yyVAL.typfields = append(yyVAL.typfields, &types.Field{Name: name, T: yyDollar[2].typ})
			}
		}
	case 24:
		yyDollar = yyS[yypt-1 : yypt+1]
//line reflow.y:219
		{
			yyVAL.typfields = yyDollar[1].typfields
		}
	case 25:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:221
		{
			yyVAL.typfields = append(yyDollar[1].typfields, yyDollar[3].typfields...)
		}
	case 26:
		yyDollar = yyS[yypt-1 : yypt+1]
//line reflow.y:225
		{
			yyVAL.typearg = typearg{yyDollar[1].typ, nil}
		}
	case 27:
		yyDollar = yyS[yypt-2 : yypt+1]
//line reflow.y:227
		{
			yyVAL.typearg = typearg{yyDollar[1].typ, yyDollar[2].typ}
		}
	case 28:
		yyDollar = yyS[yypt-1 : yypt+1]
//line reflow.y:231
		{
			yyVAL.typeargs = []typearg{yyDollar[1].typearg}
		}
	case 29:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:233
		{
			yyVAL.typeargs = append(yyDollar[1].typeargs, yyDollar[3].typearg)
		}
	case 30:
		yyDollar = yyS[yypt-1 : yypt+1]
//line reflow.y:242
		{
			var (
				fields []*types.Field
				group  []*types.T
			)
			for _, arg := range yyDollar[1].typeargs {
				group = append(group, arg.t1)
				if arg.t2 != nil { // x, y, z t2
					// We have a group: check that they are all
					// idents, and convert them accordingly.
					for _, id := range group {
						if id.Kind != types.RefKind {
							yylex.Error(fmt.Sprintf("expected identifier, found %s", id))
							goto Fail
						}
						if len(id.Path) != 1 {
							yylex.Error(fmt.Sprintf("non-simple argument name"))
							goto Fail
						}
						fields = append(fields, &types.Field{Name: id.Path[0], T: arg.t2})
					}
					group = nil
				}
			}
			if len(group) > 0 {
				if len(fields) > 0 {
					yylex.Error("cannot mix named and unnamed arguments")
					goto Fail
				}
				// Only unnamed arguments: they are all types.
				for _, t := range group {
					fields = append(fields, &types.Field{T: t})
				}
			}
			yyVAL.typfields = fields
		Fail:
		}
	case 31:
		yyDollar = yyS[yypt-1 : yypt+1]
//line reflow.y:284
		{
			yyVAL.pat = &Pat{Position: yyDollar[1].expr.Position, Kind: PatIdent, Ident: yyDollar[1].expr.Ident}
		}
	case 32:
		yyDollar = yyS[yypt-1 : yypt+1]
//line reflow.y:286
		{
			yyVAL.pat = &Pat{Position: yyDollar[1].pos.Position, Kind: PatIgnore}
		}
	case 33:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:288
		{
			yyVAL.pat = &Pat{Position: yyDollar[1].pos.Position, Kind: PatTuple, List: yyDollar[2].patlist}
		}
	case 34:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:290
		{
			yyVAL.pat = &Pat{Position: yyDollar[1].pos.Position, Kind: PatList, List: yyDollar[2].listpats.list, Tail: yyDollar[2].listpats.tail}
		}
	case 35:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:292
		{
			yyVAL.pat = &Pat{Position: yyDollar[1].pos.Position, Kind: PatStruct, Fields: make([]PatField, len(yyDollar[2].structpats))}
			for i, p := range yyDollar[2].structpats {
				yyVAL.pat.Fields[i] = PatField{p.field, p.pat}
			}
		}
	case 36:
		yyDollar = yyS[yypt-1 : yypt+1]
//line reflow.y:301
		{
			yyVAL.listpats = struct {
				list []*Pat
				tail *Pat
			}{
				list: []*Pat{yyDollar[1].pat},
			}
		}
	case 37:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:309
		{
			yyDollar[1].listpats.list = append(yyDollar[1].listpats.list, yyDollar[3].pat)
			yyVAL.listpats = yyDollar[1].listpats
		}
	case 38:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:314
		{
			yyDollar[1].listpats.tail = &Pat{Position: yyDollar[3].pos.Position, Kind: PatIgnore}
			yyVAL.listpats = yyDollar[1].listpats
		}
	case 39:
		yyDollar = yyS[yypt-4 : yypt+1]
//line reflow.y:319
		{
			yyDollar[1].listpats.tail = yyDollar[4].pat
			yyVAL.listpats = yyDollar[1].listpats
		}
	case 40:
		yyDollar = yyS[yypt-1 : yypt+1]
//line reflow.y:326
		{
			yyVAL.patlist = []*Pat{yyDollar[1].pat}
		}
	case 41:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:328
		{
			yyVAL.patlist = append(yyDollar[1].patlist, yyDollar[3].pat)
		}
	case 42:
		yyDollar = yyS[yypt-1 : yypt+1]
//line reflow.y:332
		{
			yyVAL.structpats = []struct {
				field string
				pat   *Pat
			}{yyDollar[1].structpat}
		}
	case 43:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:337
		{
			yyVAL.structpats = append(yyDollar[1].structpats, yyDollar[3].structpat)
		}
	case 44:
		yyDollar = yyS[yypt-1 : yypt+1]
//line reflow.y:341
		{
			yyVAL.structpat = struct {
				field string
				pat   *Pat
			}{yyDollar[1].expr.Ident, &Pat{Kind: PatIdent, Ident: yyDollar[1].expr.Ident}}
		}
	case 45:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:346
		{
			yyVAL.structpat = struct {
				field string
				pat   *Pat
			}{yyDollar[1].expr.Ident, yyDollar[3].pat}
		}
	case 46:
		yyDollar = yyS[yypt-0 : yypt+1]
//line reflow.y:354
		{
			yyVAL.decllist = nil
		}
	case 47:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:356
		{
			yyVAL.decllist = append(yyDollar[1].decllist, yyDollar[2].decl)
		}
	case 48:
		yyDollar = yyS[yypt-2 : yypt+1]
//line reflow.y:360
		{
			yyVAL.decllist = []*Decl{yyDollar[1].decl}
		}
	case 49:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:362
		{
			yyVAL.decllist = append(yyDollar[1].decllist, yyDollar[2].decl)
		}
	case 50:
		yyDollar = yyS[yypt-0 : yypt+1]
//line reflow.y:365
		{
			yyVAL.decllist = nil
		}
	case 51:
		yyDollar = yyS[yypt-1 : yypt+1]
//line reflow.y:367
		{
			yyVAL.decllist = []*Decl{yyDollar[1].decl}
		}
	case 52:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:369
		{
			yyVAL.decllist = append(yyDollar[1].decllist, yyDollar[3].decl)
		}
	case 54:
		yyDollar = yyS[yypt-1 : yypt+1]
//line reflow.y:373
		{
			yyVAL.decl = &Decl{
				Position: yyDollar[1].expr.Position,
				Comment:  yyDollar[1].expr.Comment,
				Pat:      &Pat{Position: yyDollar[1].expr.Position, Kind: PatIdent, Ident: yyDollar[1].expr.Ident},
				Kind:     DeclAssign,
				Expr:     &Expr{Kind: ExprIdent, Ident: yyDollar[1].expr.Ident},
			}
		}
	case 55:
		yyDollar = yyS[yypt-0 : yypt+1]
//line reflow.y:384
		{
			yyVAL.decllist = nil
		}
	case 56:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:386
		{
			yyVAL.decllist = append(yyDollar[1].decllist, yyDollar[2].decllist...)
		}
	case 59:
		yyDollar = yyS[yypt-7 : yypt+1]
//line reflow.y:391
		{
			yyDollar[7].decl.Expr = &Expr{Position: yyDollar[7].decl.Expr.Position, Kind: ExprRequires, Left: yyDollar[7].decl.Expr, Decls: yyDollar[4].decllist}
			yyDollar[7].decl.Comment = yyDollar[1].pos.comment
			yyVAL.decl = yyDollar[7].decl
		}
	case 60:
		yyDollar = yyS[yypt-2 : yypt+1]
//line reflow.y:397
		{
			yyVAL.decl = yyDollar[2].decl
			yyVAL.decl.Comment = yyDollar[1].pos.comment
		}
	case 61:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:402
		{
			yyVAL.decl = &Decl{Position: yyDollar[1].expr.Position, Comment: yyDollar[1].expr.Comment, Pat: &Pat{Position: yyDollar[1].expr.Position, Kind: PatIdent, Ident: yyDollar[1].expr.Ident}, Kind: DeclAssign, Expr: yyDollar[3].expr}
		}
	case 62:
		yyDollar = yyS[yypt-7 : yypt+1]
//line reflow.y:404
		{
			yyVAL.decl = &Decl{Position: yyDollar[1].pos.Position, Comment: yyDollar[1].pos.comment, Pat: &Pat{Position: yyDollar[1].pos.Position, Kind: PatIdent, Ident: yyDollar[2].expr.Ident}, Kind: DeclAssign, Expr: &Expr{
				Kind: ExprFunc,
				Args: yyDollar[4].typfields,
				Left: yyDollar[7].expr}}
		}
	case 63:
		yyDollar = yyS[yypt-8 : yypt+1]
//line reflow.y:409
		{
			yyVAL.decl = &Decl{Position: yyDollar[1].pos.Position, Comment: yyDollar[1].pos.comment, Pat: &Pat{Position: yyDollar[1].pos.Position, Kind: PatIdent, Ident: yyDollar[2].expr.Ident}, Kind: DeclAssign, Expr: &Expr{
				Position: yyDollar[1].pos.Position,
				Kind:     ExprAscribe,
				Type:     types.Func(yyDollar[6].typ, yyDollar[4].typfields...),
				Left:     &Expr{Kind: ExprFunc, Args: yyDollar[4].typfields, Left: yyDollar[8].expr}}}
		}
	case 64:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:417
		{
			yyVAL.decl = &Decl{Position: yyDollar[1].pos.Position, Comment: yyDollar[1].pos.comment, Kind: DeclType, Ident: yyDollar[2].expr.Ident, Type: yyDollar[3].typ}
		}
	case 65:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:421
		{
			yyVAL.decl = &Decl{Position: yyDollar[3].expr.Position, Pat: yyDollar[1].pat, Kind: DeclAssign, Expr: yyDollar[3].expr}
		}
	case 66:
		yyDollar = yyS[yypt-4 : yypt+1]
//line reflow.y:423
		{
			yyVAL.decl = &Decl{
				Position: yyDollar[4].expr.Position,
				Pat:      yyDollar[1].pat,
				Kind:     DeclAssign,
				Expr: &Expr{
					Position: yyDollar[4].expr.Position,
					Kind:     ExprAscribe,
					Type:     yyDollar[2].typ,
					Left:     yyDollar[4].expr,
				},
			}
		}
	case 67:
		yyDollar = yyS[yypt-2 : yypt+1]
//line reflow.y:439
		{
			yyVAL.decllist = nil
			for i := range yyDollar[1].posidents.idents {
				yyVAL.decllist = append(yyVAL.decllist, &Decl{
					Position: yyDollar[1].posidents.pos,
					Comment:  yyDollar[1].posidents.comments[i],
					Ident:    yyDollar[1].posidents.idents[i],
					Kind:     DeclDeclare,
					Type:     yyDollar[2].typ,
				})
			}
		}
	case 68:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:452
		{
			if len(yyDollar[1].posidents.idents) != 1 {
				yyVAL.decllist = []*Decl{{Kind: DeclError}}
			} else {
				yyVAL.decllist = []*Decl{{Position: yyDollar[1].posidents.pos, Comment: yyDollar[1].posidents.comments[0], Pat: &Pat{Position: yyDollar[1].posidents.pos, Kind: PatIdent, Ident: yyDollar[1].posidents.idents[0]}, Kind: DeclAssign, Expr: yyDollar[3].expr}}
			}
		}
	case 69:
		yyDollar = yyS[yypt-4 : yypt+1]
//line reflow.y:460
		{
			if len(yyDollar[1].posidents.idents) != 1 {
				yyVAL.decllist = []*Decl{{Kind: DeclError}}
			} else {
				yyVAL.decllist = []*Decl{{
					Position: yyDollar[1].posidents.pos,
					Comment:  yyDollar[1].posidents.comments[0],
					Pat:      &Pat{Position: yyDollar[1].posidents.pos, Kind: PatIdent, Ident: yyDollar[1].posidents.idents[0]},
					Kind:     DeclAssign,
					Expr:     &Expr{Kind: ExprAscribe, Position: yyDollar[1].posidents.pos, Type: yyDollar[2].typ, Left: yyDollar[4].expr},
				}}
			}
		}
	case 70:
		yyDollar = yyS[yypt-1 : yypt+1]
//line reflow.y:476
		{
			yyVAL.posidents = posIdents{yyDollar[1].expr.Position, []string{yyDollar[1].expr.Ident}, []string{yyDollar[1].expr.Comment}}
		}
	case 71:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:478
		{
			yyVAL.posidents = posIdents{yyDollar[1].posidents.pos, append(yyDollar[1].posidents.idents, yyDollar[3].expr.Ident), append(yyDollar[1].posidents.comments, yyDollar[3].expr.Comment)}
		}
	case 73:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:484
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].expr.Position, Kind: ExprBinop, Op: "||", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 74:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:486
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].expr.Position, Kind: ExprBinop, Op: "&&", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 75:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:488
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].expr.Position, Kind: ExprBinop, Op: "<", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 76:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:490
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].expr.Position, Kind: ExprBinop, Op: ">", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 77:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:492
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].expr.Position, Kind: ExprBinop, Op: "<=", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 78:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:494
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].expr.Position, Kind: ExprBinop, Op: ">=", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 79:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:496
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].expr.Position, Kind: ExprBinop, Op: "!=", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 80:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:498
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].expr.Position, Kind: ExprBinop, Op: "==", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 81:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:500
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].expr.Position, Kind: ExprBinop, Op: "+", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 82:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:502
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].expr.Position, Kind: ExprBinop, Op: "-", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 83:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:504
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].expr.Position, Kind: ExprBinop, Op: "*", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 84:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:506
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].expr.Position, Kind: ExprBinop, Op: "/", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 85:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:508
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].expr.Position, Kind: ExprBinop, Op: "%", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 86:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:510
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].expr.Position, Kind: ExprBinop, Op: "&", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 87:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:512
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].expr.Position, Kind: ExprBinop, Op: "<<", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 88:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:514
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].expr.Position, Kind: ExprBinop, Op: ">>", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 89:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:516
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].expr.Position, Kind: ExprBinop, Op: "~>", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 90:
		yyDollar = yyS[yypt-4 : yypt+1]
//line reflow.y:518
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Comment: yyDollar[1].pos.comment, Kind: ExprCond, Cond: yyDollar[2].expr, Left: yyDollar[3].expr, Right: yyDollar[4].expr}
		}
	case 92:
		yyDollar = yyS[yypt-4 : yypt+1]
//line reflow.y:521
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].expr.Position, Kind: ExprIndex, Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 93:
		yyDollar = yyS[yypt-5 : yypt+1]
//line reflow.y:523
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].expr.Position, Kind: ExprApply, Left: yyDollar[1].expr, Fields: yyDollar[3].exprfields}
		}
	case 94:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:525
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].expr.Position, Kind: ExprDeref, Left: yyDollar[1].expr, Ident: yyDollar[3].expr.Ident}
		}
	case 95:
		yyDollar = yyS[yypt-2 : yypt+1]
//line reflow.y:527
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Kind: ExprUnop, Op: "!", Left: yyDollar[2].expr}
		}
	case 96:
		yyDollar = yyS[yypt-2 : yypt+1]
//line reflow.y:529
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Kind: ExprUnop, Op: "-", Left: yyDollar[2].expr}
		}
	case 97:
		yyDollar = yyS[yypt-2 : yypt+1]
//line reflow.y:533
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Kind: ExprBlock, Left: yyDollar[2].expr}
		}
	case 98:
		yyDollar = yyS[yypt-5 : yypt+1]
//line reflow.y:535
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Kind: ExprCond, Cond: yyDollar[3].expr, Left: yyDollar[4].expr, Right: yyDollar[5].expr}
		}
	case 101:
		yyDollar = yyS[yypt-1 : yypt+1]
//line reflow.y:542
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Kind: ExprIdent, Ident: "file"}
		}
	case 102:
		yyDollar = yyS[yypt-1 : yypt+1]
//line reflow.y:544
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Comment: yyDollar[1].pos.comment, Kind: ExprIdent, Ident: "dir"}
		}
	case 103:
		yyDollar = yyS[yypt-6 : yypt+1]
//line reflow.y:546
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Comment: yyDollar[1].pos.comment, Kind: ExprFunc, Args: yyDollar[3].typfields, Left: yyDollar[6].expr}
		}
	case 104:
		yyDollar = yyS[yypt-7 : yypt+1]
//line reflow.y:548
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Comment: yyDollar[1].pos.comment, Kind: ExprAscribe, Type: yyDollar[5].typ, Left: &Expr{
				Position: yyDollar[7].expr.Position, Kind: ExprFunc, Args: yyDollar[3].typfields, Left: yyDollar[7].expr}}
		}
	case 105:
		yyDollar = yyS[yypt-6 : yypt+1]
//line reflow.y:551
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Comment: yyDollar[1].pos.comment, Kind: ExprExec, Decls: yyDollar[3].decllist, Type: yyDollar[5].typ, Template: yyDollar[6].template}
		}
	case 106:
		yyDollar = yyS[yypt-4 : yypt+1]
//line reflow.y:553
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Comment: yyDollar[1].pos.comment, Kind: ExprMake, Left: yyDollar[3].expr}
		}
	case 107:
		yyDollar = yyS[yypt-7 : yypt+1]
//line reflow.y:555
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Comment: yyDollar[1].pos.comment, Kind: ExprMake, Left: yyDollar[3].expr, Decls: yyDollar[5].decllist}
		}
	case 108:
		yyDollar = yyS[yypt-6 : yypt+1]
//line reflow.y:557
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Comment: yyDollar[1].pos.comment, Kind: ExprTuple, Fields: append([]*FieldExpr{{Expr: yyDollar[2].expr}}, yyDollar[4].exprfields...)}
		}
	case 109:
		yyDollar = yyS[yypt-4 : yypt+1]
//line reflow.y:559
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Comment: yyDollar[1].pos.comment, Kind: ExprStruct, Fields: yyDollar[2].exprfields}
		}
	case 110:
		yyDollar = yyS[yypt-4 : yypt+1]
//line reflow.y:561
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Comment: yyDollar[1].pos.comment, Kind: ExprList, List: yyDollar[2].exprlist}
		}
	case 111:
		yyDollar = yyS[yypt-6 : yypt+1]
//line reflow.y:563
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Comment: yyDollar[1].pos.comment, Kind: ExprList, List: yyDollar[2].exprlist}
			for _, list := range yyDollar[4].exprlist {
				yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Kind: ExprBinop, Op: "+", Left: yyVAL.expr, Right: list}
			}
		}
	case 112:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:570
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Comment: yyDollar[1].pos.comment, Kind: ExprMap}
		}
	case 113:
		yyDollar = yyS[yypt-4 : yypt+1]
//line reflow.y:572
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Comment: yyDollar[1].pos.comment, Kind: ExprMap, Map: yyDollar[2].exprmap}
		}
	case 114:
		yyDollar = yyS[yypt-6 : yypt+1]
//line reflow.y:574
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Comment: yyDollar[1].pos.comment, Kind: ExprMap, Map: yyDollar[2].exprmap}
			for _, list := range yyDollar[4].exprlist {
				yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Kind: ExprBinop, Op: "+", Left: list, Right: yyVAL.expr}
			}
		}
	case 115:
		yyDollar = yyS[yypt-5 : yypt+1]
//line reflow.y:581
		{
			yyVAL.expr = &Expr{
				Position:     yyDollar[1].pos.Position,
				Comment:      yyDollar[1].pos.comment,
				Kind:         ExprCompr,
				ComprExpr:    yyDollar[2].expr,
				ComprClauses: yyDollar[4].comprclauses,
			}
		}
	case 116:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:591
		{
			yyVAL.expr = yyDollar[2].expr
		}
	case 118:
		yyDollar = yyS[yypt-4 : yypt+1]
//line reflow.y:594
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Comment: yyDollar[1].pos.comment, Kind: ExprBuiltin, Op: "len", Left: yyDollar[3].expr}
		}
	case 119:
		yyDollar = yyS[yypt-4 : yypt+1]
//line reflow.y:596
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].expr.Position, Comment: yyDollar[1].expr.Comment, Kind: ExprBuiltin, Op: "int", Left: yyDollar[3].expr}
		}
	case 120:
		yyDollar = yyS[yypt-4 : yypt+1]
//line reflow.y:598
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].expr.Position, Comment: yyDollar[1].expr.Comment, Kind: ExprBuiltin, Op: "float", Left: yyDollar[3].expr}
		}
	case 121:
		yyDollar = yyS[yypt-6 : yypt+1]
//line reflow.y:600
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Comment: yyDollar[1].pos.comment, Kind: ExprBuiltin, Op: "zip", Left: yyDollar[3].expr, Right: yyDollar[5].expr}
		}
	case 122:
		yyDollar = yyS[yypt-4 : yypt+1]
//line reflow.y:602
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Comment: yyDollar[1].pos.comment, Kind: ExprBuiltin, Op: "unzip", Left: yyDollar[3].expr}
		}
	case 123:
		yyDollar = yyS[yypt-4 : yypt+1]
//line reflow.y:604
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Comment: yyDollar[1].pos.comment, Kind: ExprBuiltin, Op: "flatten", Left: yyDollar[3].expr}
		}
	case 124:
		yyDollar = yyS[yypt-4 : yypt+1]
//line reflow.y:606
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Comment: yyDollar[1].pos.comment, Kind: ExprBuiltin, Op: "map", Left: yyDollar[3].expr}
		}
	case 125:
		yyDollar = yyS[yypt-6 : yypt+1]
//line reflow.y:608
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Comment: yyDollar[1].pos.comment, Kind: ExprBuiltin, Op: "range", Left: yyDollar[3].expr, Right: yyDollar[5].expr}
		}
	case 126:
		yyDollar = yyS[yypt-4 : yypt+1]
//line reflow.y:610
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Comment: yyDollar[1].pos.comment, Kind: ExprBuiltin, Op: "list", Left: yyDollar[3].expr}
		}
	case 127:
		yyDollar = yyS[yypt-4 : yypt+1]
//line reflow.y:612
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Comment: yyDollar[1].pos.comment, Kind: ExprBuiltin, Op: "delay", Left: yyDollar[3].expr}
		}
	case 128:
		yyDollar = yyS[yypt-4 : yypt+1]
//line reflow.y:614
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Comment: yyDollar[1].pos.comment, Kind: ExprBuiltin, Op: "panic", Left: yyDollar[3].expr}
		}
	case 129:
		yyDollar = yyS[yypt-4 : yypt+1]
//line reflow.y:616
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Comment: yyDollar[1].pos.comment, Kind: ExprBuiltin, Op: "trace", Left: yyDollar[3].expr}
		}
	case 130:
		yyDollar = yyS[yypt-5 : yypt+1]
//line reflow.y:620
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Comment: yyDollar[1].pos.comment, Kind: ExprBlock, Decls: yyDollar[2].decllist, Left: yyDollar[3].expr}
		}
	case 131:
		yyDollar = yyS[yypt-5 : yypt+1]
//line reflow.y:624
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Comment: yyDollar[1].pos.comment, Kind: ExprBlock, Decls: yyDollar[2].decllist, Left: yyDollar[3].expr}
		}
	case 132:
		yyDollar = yyS[yypt-5 : yypt+1]
//line reflow.y:628
		{
			yyVAL.expr = &Expr{Position: yyDollar[1].pos.Position, Comment: yyDollar[1].pos.comment, Kind: ExprSwitch, Left: yyDollar[2].expr, CaseClauses: yyDollar[4].caseclauses}
		}
	case 133:
		yyDollar = yyS[yypt-0 : yypt+1]
//line reflow.y:631
		{
			yyVAL.caseclauses = nil
		}
	case 134:
		yyDollar = yyS[yypt-2 : yypt+1]
//line reflow.y:633
		{
			yyVAL.caseclauses = append(yyDollar[1].caseclauses, yyDollar[2].caseclause)
		}
	case 135:
		yyDollar = yyS[yypt-5 : yypt+1]
//line reflow.y:637
		{
			yyVAL.caseclause = &CaseClause{Position: yyDollar[1].pos.Position, Comment: yyDollar[1].pos.comment, Pat: yyDollar[2].pat, Expr: yyDollar[4].expr}
		}
	case 138:
		yyDollar = yyS[yypt-2 : yypt+1]
//line reflow.y:643
		{
			yyVAL.expr = &Expr{Kind: ExprBlock, Decls: yyDollar[1].decllist, Left: yyDollar[2].expr}
		}
	case 139:
		yyDollar = yyS[yypt-1 : yypt+1]
//line reflow.y:647
		{
			yyVAL.comprclauses = []*ComprClause{yyDollar[1].comprclause}
		}
	case 140:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:649
		{
			yyVAL.comprclauses = append(yyDollar[1].comprclauses, yyDollar[3].comprclause)
		}
	case 141:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:653
		{
			yyVAL.comprclause = &ComprClause{Kind: ComprEnum, Pat: yyDollar[1].pat, Expr: yyDollar[3].expr}
		}
	case 142:
		yyDollar = yyS[yypt-2 : yypt+1]
//line reflow.y:655
		{
			yyVAL.comprclause = &ComprClause{Kind: ComprFilter, Expr: yyDollar[2].expr}
		}
	case 145:
		yyDollar = yyS[yypt-1 : yypt+1]
//line reflow.y:662
		{
			yyVAL.exprfields = []*FieldExpr{yyDollar[1].exprfield}
		}
	case 146:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:664
		{
			yyVAL.exprfields = append(yyDollar[1].exprfields, yyDollar[3].exprfield)
		}
	case 147:
		yyDollar = yyS[yypt-1 : yypt+1]
//line reflow.y:668
		{
			yyVAL.exprfield = &FieldExpr{Name: yyDollar[1].expr.Ident, Expr: &Expr{Position: yyDollar[1].expr.Position, Kind: ExprIdent, Ident: yyDollar[1].expr.Ident}}
		}
	case 148:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:670
		{
			yyVAL.exprfield = &FieldExpr{Name: yyDollar[1].expr.Ident, Expr: yyDollar[3].expr}
		}
	case 149:
		yyDollar = yyS[yypt-0 : yypt+1]
//line reflow.y:673
		{
			yyVAL.exprlist = nil
		}
	case 150:
		yyDollar = yyS[yypt-1 : yypt+1]
//line reflow.y:675
		{
			yyVAL.exprlist = []*Expr{yyDollar[1].expr}
		}
	case 151:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:677
		{
			yyVAL.exprlist = append(yyDollar[1].exprlist, yyDollar[3].expr)
		}
	case 152:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:681
		{
			yyVAL.exprlist = []*Expr{yyDollar[2].expr}
		}
	case 153:
		yyDollar = yyS[yypt-4 : yypt+1]
//line reflow.y:683
		{
			yyVAL.exprlist = append(yyDollar[1].exprlist, yyDollar[3].expr)
		}
	case 154:
		yyDollar = yyS[yypt-1 : yypt+1]
//line reflow.y:687
		{
			yyVAL.exprfields = []*FieldExpr{{Expr: yyDollar[1].expr}}
		}
	case 155:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:689
		{
			yyVAL.exprfields = append(yyDollar[1].exprfields, &FieldExpr{Expr: yyDollar[3].expr})
		}
	case 156:
		yyDollar = yyS[yypt-1 : yypt+1]
//line reflow.y:693
		{
			yyVAL.exprfields = []*FieldExpr{{Expr: yyDollar[1].expr}}
		}
	case 157:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:695
		{
			yyVAL.exprfields = append(yyDollar[1].exprfields, &FieldExpr{Expr: yyDollar[3].expr})
		}
	case 158:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:699
		{
			yyVAL.exprmap = map[*Expr]*Expr{yyDollar[1].expr: yyDollar[3].expr}
		}
	case 159:
		yyDollar = yyS[yypt-5 : yypt+1]
//line reflow.y:701
		{
			yyVAL.exprmap = yyDollar[1].exprmap
			yyVAL.exprmap[yyDollar[3].expr] = yyDollar[5].expr
		}
	case 161:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:712
		{
			yyVAL.module = &ModuleImpl{Keyspace: yyDollar[1].expr, ParamDecls: yyDollar[2].decllist, Decls: yyDollar[3].decllist}
		}
	case 162:
		yyDollar = yyS[yypt-0 : yypt+1]
//line reflow.y:715
		{
			yyVAL.expr = nil
		}
	case 163:
		yyDollar = yyS[yypt-2 : yypt+1]
//line reflow.y:717
		{
			yyVAL.expr = yyDollar[2].expr
		}
	case 164:
		yyDollar = yyS[yypt-0 : yypt+1]
//line reflow.y:720
		{
			yyVAL.decllist = nil
		}
	case 165:
		yyDollar = yyS[yypt-3 : yypt+1]
//line reflow.y:722
		{
			yyVAL.decllist = append(yyDollar[1].decllist, yyDollar[2].decllist...)
		}
	case 166:
		yyDollar = yyS[yypt-0 : yypt+1]
//line reflow.y:725
		{
			yyVAL.decllist = nil
		}
	case 167:
		yyDollar = yyS[yypt-2 : yypt+1]
//line reflow.y:727
		{
			yyVAL.decllist = yyDollar[2].decllist
		}
	case 168:
		yyDollar = yyS[yypt-4 : yypt+1]
//line reflow.y:729
		{
			yyVAL.decllist = yyDollar[3].decllist
		}
	}
	goto yystack /* stack new state and value */
}
