// Copyright 2017 GRAIL, Inc. All rights reserved.
// Use of this source code is governed by the Apache 2.0
// license that can be found in the LICENSE file.

// Code generated by "stringer -type=Op"; DO NOT EDIT

package lang

import "fmt"

const _Op_name = "opIdentopApplyopConstopInternopExternopDefopImageopCollectopGroupbyopMapopFuncopVarfuncopExecopParamopConcatopPullupopLet"

var _Op_index = [...]uint8{0, 7, 14, 21, 29, 37, 42, 49, 58, 67, 72, 78, 87, 93, 100, 108, 116, 121}

func (i Op) String() string {
	i -= 1
	if i < 0 || i >= Op(len(_Op_index)-1) {
		return fmt.Sprintf("Op(%d)", i+1)
	}
	return _Op_name[_Op_index[i]:_Op_index[i+1]]
}
