// Code generated by "stringer -type=Phase"; DO NOT EDIT

package runner

import "fmt"

const _Phase_name = "InitEvalRetryDone"

var _Phase_index = [...]uint8{0, 4, 8, 13, 17}

func (i Phase) String() string {
	if i < 0 || i >= Phase(len(_Phase_index)-1) {
		return fmt.Sprintf("Phase(%d)", i)
	}
	return _Phase_name[_Phase_index[i]:_Phase_index[i+1]]
}
